openapi: 3.1.0
info:
  title: qoery's API
  version: 0.1.0
  description: |
    Every number on the internet, queryable. Instant access to millions of trusted
    statistics through a single natural language query or API call.

    # Installation

    ### Python SDK

    Install from PyPI:

    ```bash
    pip install qoery
    ```

    PyPI: [qoery](https://pypi.org/project/qoery/)

    ### JavaScript SDK

    Install from npm:

    ```bash
    npm install qoery
    ```

    npm: [qoery](https://www.npmjs.com/package/qoery)

  contact:
    name: qoery Support
    url: https://qoery.com
    email: samuel.tinnerholm@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.qoery.com/v0

security:
  - ApiKeyAuth: []

tags:
  - name: Queries
    description: Natural language and SQL query execution
  - name: Web Scraping
    description: Web scraping and data extraction
  - name: Usage
    description: Usage statistics and rate limiting

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication, provided via the 'X-API-Key' header.

  schemas:
    ErrorResponse:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/ErrorResponse'
    UsageStats:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/UsageStats'
    ObservationData:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/ObservationData'
    QueryResponse:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/QueryResponse'
    NLQueryRequest:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/NLQueryRequest'
    SQLQueryRequest:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/SQLQueryRequest'
    URLRequest:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/URLRequest'
    ScrapeResponse:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/ScrapeResponse'

  responses:
    UnauthorizedError:
      $ref: 'api/responses/responses.yaml#/components/responses/UnauthorizedError'
    RateLimitError:
      $ref: 'api/responses/responses.yaml#/components/responses/RateLimitError'
    RateLimitHeaders:
      $ref: 'api/responses/responses.yaml#/components/responses/RateLimitHeaders'

paths:
  /query/nl:
    $ref: 'api/paths/queries.yaml#/paths/~1query~1nl'
  /query/sql:
    $ref: 'api/paths/queries.yaml#/paths/~1query~1sql'
  /scrape:
    $ref: 'api/paths/web-scraping.yaml#/paths/~1scrape'
  /usage:
    $ref: 'api/paths/usage.yaml#/paths/~1usage'
