openapi: 3.1.0
info:
  title: qoery's API
  version: 0.1.0
  description: >
    Every number on the internet, queryable. Instant access to millions of trusted
    statistics through a single natural language query or API call.

servers:
  - url: https://api.qoery.com
  - url: http://localhost:8000

tags:
  - name: Queries
    description: Natural language and SQL query execution
  - name: Data Sources
    description: Web scraping and data extraction
  - name: Usage
    description: Usage statistics and rate limiting

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication

  schemas:
    ErrorResponse:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/ErrorResponse'
    UsageStats:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/UsageStats'
    Observation:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/Observation'
    Series:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/Series'
    QueryResponse:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/QueryResponse'
    NLQueryRequest:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/NLQueryRequest'
    SQLQueryRequest:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/SQLQueryRequest'
    URLRequest:
      $ref: 'api/schemas/schemas.yaml#/components/schemas/URLRequest'

  responses:
    UnauthorizedError:
      $ref: 'api/responses/responses.yaml#/components/responses/UnauthorizedError'
    RateLimitError:
      $ref: 'api/responses/responses.yaml#/components/responses/RateLimitError'
    RateLimitHeaders:
      $ref: 'api/responses/responses.yaml#/components/responses/RateLimitHeaders'

paths:
  /query/nl:
    $ref: 'api/paths/queries.yaml#/paths/~1query~1nl'
  /query/sql:
    $ref: 'api/paths/queries.yaml#/paths/~1query~1sql'
  /scrape:
    $ref: 'api/paths/data-sources.yaml#/paths/~1scrape'
  /usage:
    $ref: 'api/paths/usage.yaml#/paths/~1usage'
