openapi: 3.1.0
info:
  title: qoery's API
  version: 0.1.0
  description: >
    Every number on the internet, queryable. Instant access to millions of trusted
    statistics through a single natural language query or API call.

servers:
  - url: https://api.qoery.com
  - url: http://localhost:8000

tags:
  - name: Authentication
    description: API key management and authentication
  - name: Usage
    description: Usage statistics and rate limiting
  - name: Queries
    description: Natural language and SQL query execution
  - name: Data Sources
    description: Web scraping and data extraction

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication
    SupabaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase JWT token for user authentication

  schemas:
    $ref: 'api/schemas/schemas.yaml#/components/schemas'

  responses:
    $ref: 'api/responses/responses.yaml#/components/responses'

paths:
  /auth/keys:
    $ref: 'api/paths/auth.yaml#/paths/auth/keys'
  /auth/keys/{key_id}:
    $ref: 'api/paths/auth.yaml#/paths/auth/keys/{key_id}'
  /usage:
    $ref: 'api/paths/usage.yaml#/paths/usage'
  /query/nl:
    $ref: 'api/paths/queries.yaml#/paths/query/nl'
  /query/sql:
    $ref: 'api/paths/queries.yaml#/paths/query/sql'
  /scrape:
    $ref: 'api/paths/data-sources.yaml#/paths/scrape'
