/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetDatasetJobStatus200Response from '../model/GetDatasetJobStatus200Response';
import ListDatasetsOrStartJob200Response from '../model/ListDatasetsOrStartJob200Response';
import ListDatasetsOrStartJob200ResponseOneOf1 from '../model/ListDatasetsOrStartJob200ResponseOneOf1';
import ListDatasetsOrStartJob400Response from '../model/ListDatasetsOrStartJob400Response';
import ListDatasetsOrStartJob429Response from '../model/ListDatasetsOrStartJob429Response';
import StartDatasetJobRequest from '../model/StartDatasetJobRequest';

/**
* Datasets service.
* @module api/DatasetsApi
* @version 0.5.0
*/
export default class DatasetsApi {

    /**
    * Constructs a new DatasetsApi. 
    * @alias module:api/DatasetsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the downloadDatasetCsv operation.
     * @callback module:api/DatasetsApi~downloadDatasetCsvCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download the CSV file
     * Downloads the CSV file containing the collected dataset. The file may be partial if the job is still processing.  **CSV Format:** - First row contains column headers - Each subsequent row represents a data point - Columns include: `url`, `title`, `value`, `dimension`, `timestamp` (if applicable) - Data is sorted by relevance score (most relevant first) - Partial CSVs are available while jobs are processing 
     * @param {String} jobId Unique identifier for the job
     * @param {module:api/DatasetsApi~downloadDatasetCsvCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    downloadDatasetCsv(jobId, callback) {
      let postBody = null;
      // verify the required parameter 'jobId' is set
      if (jobId === undefined || jobId === null) {
        throw new Error("Missing the required parameter 'jobId' when calling downloadDatasetCsv");
      }

      let pathParams = {
        'job_id': jobId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeader', 'ApiKeyAuth', 'BearerAuth'];
      let contentTypes = [];
      let accepts = ['text/csv', 'application/json'];
      let returnType = File;
      return this.apiClient.callApi(
        '/v0/datasets/{job_id}/csv', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDatasetJobStatus operation.
     * @callback module:api/DatasetsApi~getDatasetJobStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetDatasetJobStatus200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get job status and progress
     * Returns the current status and progress of a dataset collection job. Poll this endpoint to check when the job completes.  **Status Values:** - `processing`: Job is actively collecting data - `completed`: Job finished successfully, CSV is ready - `error`: Job failed, check the `error` field for details  **Progress Steps:** - `initializing`: Setting up the job - `searching`: Finding relevant URLs - `scraping`: Extracting data from URLs - `processing`: Analyzing and structuring data - `finalizing`: Preparing the CSV output 
     * @param {String} jobId Unique identifier for the job
     * @param {module:api/DatasetsApi~getDatasetJobStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetDatasetJobStatus200Response}
     */
    getDatasetJobStatus(jobId, callback) {
      let postBody = null;
      // verify the required parameter 'jobId' is set
      if (jobId === undefined || jobId === null) {
        throw new Error("Missing the required parameter 'jobId' when calling getDatasetJobStatus");
      }

      let pathParams = {
        'job_id': jobId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeader', 'ApiKeyAuth', 'BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetDatasetJobStatus200Response;
      return this.apiClient.callApi(
        '/v0/datasets/{job_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listDatasetsOrStartJob operation.
     * @callback module:api/DatasetsApi~listDatasetsOrStartJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListDatasetsOrStartJob200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List API endpoints or start a dataset collection job
     * If no `search` query parameter is provided, returns API information. If `search` parameter is provided, starts a new dataset collection job.  **Job Lifecycle:** - Jobs start in `processing` status - Poll the job status endpoint to check progress - Jobs transition to `completed` when finished or `error` if they fail - Typical job duration: 1-5 minutes depending on query complexity - CSV files are available for download even while processing (partial data) 
     * @param {Object} opts Optional parameters
     * @param {String} [search] Search query to start a dataset collection job
     * @param {module:api/DatasetsApi~listDatasetsOrStartJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListDatasetsOrStartJob200Response}
     */
    listDatasetsOrStartJob(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeader', 'ApiKeyAuth', 'BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListDatasetsOrStartJob200Response;
      return this.apiClient.callApi(
        '/v0/datasets', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the startDatasetJob operation.
     * @callback module:api/DatasetsApi~startDatasetJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListDatasetsOrStartJob200ResponseOneOf1} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Start a new dataset collection job
     * Starts a new dataset collection job with the provided search query. The job runs asynchronously in the background.  **Job Lifecycle:** - Jobs start in `processing` status - Poll the job status endpoint to check progress - Jobs transition to `completed` when finished or `error` if they fail - Typical job duration: 1-5 minutes depending on query complexity - CSV files are available for download even while processing (partial data) 
     * @param {Object} opts Optional parameters
     * @param {String} [search] Search query (alternative to request body)
     * @param {module:model/StartDatasetJobRequest} [startDatasetJobRequest] Request body with search query. Alternatively, you can provide `search` as a query parameter. 
     * @param {module:api/DatasetsApi~startDatasetJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListDatasetsOrStartJob200ResponseOneOf1}
     */
    startDatasetJob(opts, callback) {
      opts = opts || {};
      let postBody = opts['startDatasetJobRequest'];

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeader', 'ApiKeyAuth', 'BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ListDatasetsOrStartJob200ResponseOneOf1;
      return this.apiClient.callApi(
        '/v0/datasets', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
