/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import QueryNlPost200Response from '../model/QueryNlPost200Response';
import QueryNlPost400Response from '../model/QueryNlPost400Response';
import QueryNlPostRequest from '../model/QueryNlPostRequest';
import QuerySqlPost200Response from '../model/QuerySqlPost200Response';
import QuerySqlPostRequest from '../model/QuerySqlPostRequest';

/**
* Queries service.
* @module api/QueriesApi
* @version 0.1.0
*/
export default class QueriesApi {

    /**
    * Constructs a new QueriesApi. 
    * @alias module:api/QueriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the queryNlPost operation.
     * @callback module:api/QueriesApi~queryNlPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/QueryNlPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Natural Language Query
     * Submit a natural-language request and get back a curated time series response. The response also includes the generated SQL so you can switch to the SQL endpoint for faster/cheaper repeated queries.
     * @param {Object} opts Optional parameters
     * @param {module:model/QueryNlPostRequest} [queryNlPostRequest] Provide JSON body or use query parameter 'query'. Body takes precedence.
     * @param {module:api/QueriesApi~queryNlPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/QueryNlPost200Response}
     */
    queryNlPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['queryNlPostRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = QueryNlPost200Response;
      return this.apiClient.callApi(
        '/query/nl', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the querySqlPost operation.
     * @callback module:api/QueriesApi~querySqlPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/QuerySqlPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * SQL Query
     * Execute a read-only SELECT query and receive the results as curated time series. The response includes the executed SQL query and optional metadata.
     * @param {Object} opts Optional parameters
     * @param {module:model/QuerySqlPostRequest} [querySqlPostRequest] Provide JSON body with 'query' or 'sql_query' field, or use query parameters. Body takes precedence.
     * @param {module:api/QueriesApi~querySqlPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/QuerySqlPost200Response}
     */
    querySqlPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['querySqlPostRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = QuerySqlPost200Response;
      return this.apiClient.callApi(
        '/query/sql', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
