/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetUsageStats200Response from '../model/GetUsageStats200Response';
import ListDatasetsOrStartJob400Response from '../model/ListDatasetsOrStartJob400Response';

/**
* Usage service.
* @module api/UsageApi
* @version 0.5.0
*/
export default class UsageApi {

    /**
    * Constructs a new UsageApi. 
    * @alias module:api/UsageApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getUsageStats operation.
     * @callback module:api/UsageApi~getUsageStatsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetUsageStats200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get usage statistics
     * Returns current usage statistics and quota information for the user. Can be identified by either `api_key` or `uid` parameter.  **Usage Period:** - Usage is tracked monthly, resetting on the 1st of each month - Counts include all API calls, including errors - Errors are tracked separately in the `errors` field 
     * @param {Object} opts Optional parameters
     * @param {String} [apiKey] API key to look up usage for (alternative to uid)
     * @param {String} [uid] User ID to look up usage for (alternative to api_key)
     * @param {String} [xApiKey] API key provided via header
     * @param {String} [authorization] API key provided as Bearer token
     * @param {module:api/UsageApi~getUsageStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetUsageStats200Response}
     */
    getUsageStats(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'api_key': opts['apiKey'],
        'uid': opts['uid']
      };
      let headerParams = {
        'x-api-key': opts['xApiKey'],
        'Authorization': opts['authorization']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetUsageStats200Response;
      return this.apiClient.callApi(
        '/v0/usage', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
