/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import QueryNlPost400Response from '../model/QueryNlPost400Response';
import UsageGet200Response from '../model/UsageGet200Response';

/**
* Usage service.
* @module api/UsageApi
* @version 0.1.0
*/
export default class UsageApi {

    /**
    * Constructs a new UsageApi. 
    * @alias module:api/UsageApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the usageGet operation.
     * @callback module:api/UsageApi~usageGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UsageGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get usage statistics
     * Get current usage and rate limit information per endpoint
     * @param {String} uid User ID (UUID)
     * @param {module:api/UsageApi~usageGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UsageGet200Response}
     */
    usageGet(uid, callback) {
      let postBody = null;
      // verify the required parameter 'uid' is set
      if (uid === undefined || uid === null) {
        throw new Error("Missing the required parameter 'uid' when calling usageGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'uid': uid
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UsageGet200Response;
      return this.apiClient.callApi(
        '/usage', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
