/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import QueryNlGet200Response from '../model/QueryNlGet200Response';
import QueryNlGet400Response from '../model/QueryNlGet400Response';
import ScrapeGet200Response from '../model/ScrapeGet200Response';

/**
* WebScraping service.
* @module api/WebScrapingApi
* @version 0.4.0
*/
export default class WebScrapingApi {

    /**
    * Constructs a new WebScrapingApi. 
    * @alias module:api/WebScrapingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the plot2tableGet operation.
     * @callback module:api/WebScrapingApi~plot2tableGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/QueryNlGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Convert Charts to Data Tables
     * Provide an image URL of a plot or chart and receive the underlying datapoints as structured series. Supports time series, categorical, and scatter charts.  Credits: 1 Plot2Table credit per image processed. 
     * @param {String} imageUrl URL of the image containing charts or graphs to convert to data table
     * @param {module:api/WebScrapingApi~plot2tableGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/QueryNlGet200Response}
     */
    plot2tableGet(imageUrl, callback) {
      let postBody = null;
      // verify the required parameter 'imageUrl' is set
      if (imageUrl === undefined || imageUrl === null) {
        throw new Error("Missing the required parameter 'imageUrl' when calling plot2tableGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'image_url': imageUrl
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = QueryNlGet200Response;
      return this.apiClient.callApi(
        '/plot2table', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the scrapeGet operation.
     * @callback module:api/WebScrapingApi~scrapeGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ScrapeGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Structured Web Scrape
     * We search the public web for the most relevant sources to your query, extract structured data, and return curated series.  How it works: - We always extract tabular/JSON-like data when available. - If `paragraph_extraction` is true, we scan prose paragraphs to identify statistics and convert them into series (e.g., \"In 2000, there were 5,000 Swedes in Norway; in 2020, 50,000\" → year/value pairs). - If `plot2table` > 0, we analyze images of plots and extract their underlying datapoints.  Credits: - 1 Scrape credit per request. - Paragraph extraction surcharge = +1 credit when `paragraph_extraction` is true. - Plot2Table credits = 1 per chart processed when `plot2table` > 0. 
     * @param {String} url URL to scrape
     * @param {Object} opts Optional parameters
     * @param {String} [query] Optional hint to guide extraction focus for this URL
     * @param {Boolean} [paragraphExtraction = false)] Extract statistics from paragraphs and convert to structured series
     * @param {Number} [plot2table = 0)] Number of plot images to analyze and convert into raw datapoints
     * @param {module:api/WebScrapingApi~scrapeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ScrapeGet200Response}
     */
    scrapeGet(url, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'url' is set
      if (url === undefined || url === null) {
        throw new Error("Missing the required parameter 'url' when calling scrapeGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'url': url,
        'query': opts['query'],
        'paragraph_extraction': opts['paragraphExtraction'],
        'plot2table': opts['plot2table']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ScrapeGet200Response;
      return this.apiClient.callApi(
        '/scrape', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
