/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Qoery);
  }
}(this, function(expect, Qoery) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Qoery.ObservationData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ObservationData', function() {
    it('should create an instance of ObservationData', function() {
      // uncomment below and update the code to test ObservationData
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be.a(Qoery.ObservationData);
    });

    it('should have the property ts (base name: "ts")', function() {
      // uncomment below and update the code to test the property ts
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property entityName (base name: "entity_name")', function() {
      // uncomment below and update the code to test the property entityName
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property entityId (base name: "entity_id")', function() {
      // uncomment below and update the code to test the property entityId
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property metricName (base name: "metric_name")', function() {
      // uncomment below and update the code to test the property metricName
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property metricId (base name: "metric_id")', function() {
      // uncomment below and update the code to test the property metricId
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property unitName (base name: "unit_name")', function() {
      // uncomment below and update the code to test the property unitName
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property unitId (base name: "unit_id")', function() {
      // uncomment below and update the code to test the property unitId
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property frequency (base name: "frequency")', function() {
      // uncomment below and update the code to test the property frequency
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property seriesDescription (base name: "series_description")', function() {
      // uncomment below and update the code to test the property seriesDescription
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property labels (base name: "labels")', function() {
      // uncomment below and update the code to test the property labels
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

    it('should have the property seriesId (base name: "series_id")', function() {
      // uncomment below and update the code to test the property seriesId
      //var instance = new Qoery.ObservationData();
      //expect(instance).to.be();
    });

  });

}));
