/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QoerysApi);
  }
}(this, function(expect, QoerysApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QoerysApi.UsageStats();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsageStats', function() {
    it('should create an instance of UsageStats', function() {
      // uncomment below and update the code to test UsageStats
      //var instance = new QoerysApi.UsageStats();
      //expect(instance).to.be.a(QoerysApi.UsageStats);
    });

    it('should have the property queriesUsed (base name: "queries_used")', function() {
      // uncomment below and update the code to test the property queriesUsed
      //var instance = new QoerysApi.UsageStats();
      //expect(instance).to.be();
    });

    it('should have the property queriesLimit (base name: "queries_limit")', function() {
      // uncomment below and update the code to test the property queriesLimit
      //var instance = new QoerysApi.UsageStats();
      //expect(instance).to.be();
    });

    it('should have the property periodStart (base name: "period_start")', function() {
      // uncomment below and update the code to test the property periodStart
      //var instance = new QoerysApi.UsageStats();
      //expect(instance).to.be();
    });

    it('should have the property periodEnd (base name: "period_end")', function() {
      // uncomment below and update the code to test the property periodEnd
      //var instance = new QoerysApi.UsageStats();
      //expect(instance).to.be();
    });

    it('should have the property concurrentRequests (base name: "concurrent_requests")', function() {
      // uncomment below and update the code to test the property concurrentRequests
      //var instance = new QoerysApi.UsageStats();
      //expect(instance).to.be();
    });

    it('should have the property maxConcurrent (base name: "max_concurrent")', function() {
      // uncomment below and update the code to test the property maxConcurrent
      //var instance = new QoerysApi.UsageStats();
      //expect(instance).to.be();
    });

  });

}));
