/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Qoery);
  }
}(this, function(expect, Qoery) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Qoery.UsageGet200ResponseEndpointsNl();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsageGet200ResponseEndpointsNl', function() {
    it('should create an instance of UsageGet200ResponseEndpointsNl', function() {
      // uncomment below and update the code to test UsageGet200ResponseEndpointsNl
      //var instance = new Qoery.UsageGet200ResponseEndpointsNl();
      //expect(instance).to.be.a(Qoery.UsageGet200ResponseEndpointsNl);
    });

    it('should have the property callsUsed (base name: "calls_used")', function() {
      // uncomment below and update the code to test the property callsUsed
      //var instance = new Qoery.UsageGet200ResponseEndpointsNl();
      //expect(instance).to.be();
    });

    it('should have the property callsLimit (base name: "calls_limit")', function() {
      // uncomment below and update the code to test the property callsLimit
      //var instance = new Qoery.UsageGet200ResponseEndpointsNl();
      //expect(instance).to.be();
    });

    it('should have the property tokensIn (base name: "tokens_in")', function() {
      // uncomment below and update the code to test the property tokensIn
      //var instance = new Qoery.UsageGet200ResponseEndpointsNl();
      //expect(instance).to.be();
    });

    it('should have the property tokensOut (base name: "tokens_out")', function() {
      // uncomment below and update the code to test the property tokensOut
      //var instance = new Qoery.UsageGet200ResponseEndpointsNl();
      //expect(instance).to.be();
    });

    it('should have the property errors (base name: "errors")', function() {
      // uncomment below and update the code to test the property errors
      //var instance = new Qoery.UsageGet200ResponseEndpointsNl();
      //expect(instance).to.be();
    });

    it('should have the property remaining (base name: "remaining")', function() {
      // uncomment below and update the code to test the property remaining
      //var instance = new Qoery.UsageGet200ResponseEndpointsNl();
      //expect(instance).to.be();
    });

  });

}));
