/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Qoery);
  }
}(this, function(expect, Qoery) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Qoery.V0PlansGet200ResponsePlansValue();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V0PlansGet200ResponsePlansValue', function() {
    it('should create an instance of V0PlansGet200ResponsePlansValue', function() {
      // uncomment below and update the code to test V0PlansGet200ResponsePlansValue
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be.a(Qoery.V0PlansGet200ResponsePlansValue);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property billing (base name: "billing")', function() {
      // uncomment below and update the code to test the property billing
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property limits (base name: "limits")', function() {
      // uncomment below and update the code to test the property limits
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property apiKeys (base name: "api_keys")', function() {
      // uncomment below and update the code to test the property apiKeys
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property support (base name: "support")', function() {
      // uncomment below and update the code to test the property support
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property monthlyPrice (base name: "monthlyPrice")', function() {
      // uncomment below and update the code to test the property monthlyPrice
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property annualPrice (base name: "annualPrice")', function() {
      // uncomment below and update the code to test the property annualPrice
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

    it('should have the property discountPercentage (base name: "discountPercentage")', function() {
      // uncomment below and update the code to test the property discountPercentage
      //var instance = new Qoery.V0PlansGet200ResponsePlansValue();
      //expect(instance).to.be();
    });

  });

}));
