/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ErrorResponse from './model/ErrorResponse';
import NLQueryRequest from './model/NLQueryRequest';
import NLQueryResponse from './model/NLQueryResponse';
import ObservationData from './model/ObservationData';
import QueryNlPost200Response from './model/QueryNlPost200Response';
import QueryNlPost200ResponseSeriesInner from './model/QueryNlPost200ResponseSeriesInner';
import QueryNlPost400Response from './model/QueryNlPost400Response';
import QueryNlPostRequest from './model/QueryNlPostRequest';
import QueryResponse from './model/QueryResponse';
import QuerySqlPost200Response from './model/QuerySqlPost200Response';
import QuerySqlPost200ResponseMetadata from './model/QuerySqlPost200ResponseMetadata';
import QuerySqlPostRequest from './model/QuerySqlPostRequest';
import SQLQueryRequest from './model/SQLQueryRequest';
import ScrapePost200Response from './model/ScrapePost200Response';
import ScrapePost200ResponseArtifacts from './model/ScrapePost200ResponseArtifacts';
import ScrapePost200ResponseMetadata from './model/ScrapePost200ResponseMetadata';
import ScrapePostRequest from './model/ScrapePostRequest';
import ScrapeResponse from './model/ScrapeResponse';
import URLRequest from './model/URLRequest';
import UsageGet200Response from './model/UsageGet200Response';
import UsageGet200ResponseEndpoints from './model/UsageGet200ResponseEndpoints';
import UsageGet200ResponseEndpointsNl from './model/UsageGet200ResponseEndpointsNl';
import UsageStats from './model/UsageStats';
import QueriesApi from './api/QueriesApi';
import UsageApi from './api/UsageApi';
import WebScrapingApi from './api/WebScrapingApi';


/**
* Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Qoery = require('index'); // See note below*.
* var xxxSvc = new Qoery.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Qoery.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Qoery.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Qoery.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The NLQueryRequest model constructor.
     * @property {module:model/NLQueryRequest}
     */
    NLQueryRequest,

    /**
     * The NLQueryResponse model constructor.
     * @property {module:model/NLQueryResponse}
     */
    NLQueryResponse,

    /**
     * The ObservationData model constructor.
     * @property {module:model/ObservationData}
     */
    ObservationData,

    /**
     * The QueryNlPost200Response model constructor.
     * @property {module:model/QueryNlPost200Response}
     */
    QueryNlPost200Response,

    /**
     * The QueryNlPost200ResponseSeriesInner model constructor.
     * @property {module:model/QueryNlPost200ResponseSeriesInner}
     */
    QueryNlPost200ResponseSeriesInner,

    /**
     * The QueryNlPost400Response model constructor.
     * @property {module:model/QueryNlPost400Response}
     */
    QueryNlPost400Response,

    /**
     * The QueryNlPostRequest model constructor.
     * @property {module:model/QueryNlPostRequest}
     */
    QueryNlPostRequest,

    /**
     * The QueryResponse model constructor.
     * @property {module:model/QueryResponse}
     */
    QueryResponse,

    /**
     * The QuerySqlPost200Response model constructor.
     * @property {module:model/QuerySqlPost200Response}
     */
    QuerySqlPost200Response,

    /**
     * The QuerySqlPost200ResponseMetadata model constructor.
     * @property {module:model/QuerySqlPost200ResponseMetadata}
     */
    QuerySqlPost200ResponseMetadata,

    /**
     * The QuerySqlPostRequest model constructor.
     * @property {module:model/QuerySqlPostRequest}
     */
    QuerySqlPostRequest,

    /**
     * The SQLQueryRequest model constructor.
     * @property {module:model/SQLQueryRequest}
     */
    SQLQueryRequest,

    /**
     * The ScrapePost200Response model constructor.
     * @property {module:model/ScrapePost200Response}
     */
    ScrapePost200Response,

    /**
     * The ScrapePost200ResponseArtifacts model constructor.
     * @property {module:model/ScrapePost200ResponseArtifacts}
     */
    ScrapePost200ResponseArtifacts,

    /**
     * The ScrapePost200ResponseMetadata model constructor.
     * @property {module:model/ScrapePost200ResponseMetadata}
     */
    ScrapePost200ResponseMetadata,

    /**
     * The ScrapePostRequest model constructor.
     * @property {module:model/ScrapePostRequest}
     */
    ScrapePostRequest,

    /**
     * The ScrapeResponse model constructor.
     * @property {module:model/ScrapeResponse}
     */
    ScrapeResponse,

    /**
     * The URLRequest model constructor.
     * @property {module:model/URLRequest}
     */
    URLRequest,

    /**
     * The UsageGet200Response model constructor.
     * @property {module:model/UsageGet200Response}
     */
    UsageGet200Response,

    /**
     * The UsageGet200ResponseEndpoints model constructor.
     * @property {module:model/UsageGet200ResponseEndpoints}
     */
    UsageGet200ResponseEndpoints,

    /**
     * The UsageGet200ResponseEndpointsNl model constructor.
     * @property {module:model/UsageGet200ResponseEndpointsNl}
     */
    UsageGet200ResponseEndpointsNl,

    /**
     * The UsageStats model constructor.
     * @property {module:model/UsageStats}
     */
    UsageStats,

    /**
    * The QueriesApi service constructor.
    * @property {module:api/QueriesApi}
    */
    QueriesApi,

    /**
    * The UsageApi service constructor.
    * @property {module:api/UsageApi}
    */
    UsageApi,

    /**
    * The WebScrapingApi service constructor.
    * @property {module:api/WebScrapingApi}
    */
    WebScrapingApi
};
