/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiInfo from './model/ApiInfo';
import EndpointUsage from './model/EndpointUsage';
import ErrorResponse from './model/ErrorResponse';
import GetDatasetJobStatus200Response from './model/GetDatasetJobStatus200Response';
import GetDatasetJobStatus200ResponseProgress from './model/GetDatasetJobStatus200ResponseProgress';
import GetUsageStats200Response from './model/GetUsageStats200Response';
import GetUsageStats200ResponseEndpointBreakdownInner from './model/GetUsageStats200ResponseEndpointBreakdownInner';
import HealthResponse from './model/HealthResponse';
import JobProgress from './model/JobProgress';
import JobStartRequest from './model/JobStartRequest';
import JobStartResponse from './model/JobStartResponse';
import JobStatus from './model/JobStatus';
import ListDatasetsOrStartJob200Response from './model/ListDatasetsOrStartJob200Response';
import ListDatasetsOrStartJob200ResponseOneOf from './model/ListDatasetsOrStartJob200ResponseOneOf';
import ListDatasetsOrStartJob200ResponseOneOf1 from './model/ListDatasetsOrStartJob200ResponseOneOf1';
import ListDatasetsOrStartJob400Response from './model/ListDatasetsOrStartJob400Response';
import ListDatasetsOrStartJob429Response from './model/ListDatasetsOrStartJob429Response';
import ListPlans200Response from './model/ListPlans200Response';
import ListPlans200ResponsePlansValue from './model/ListPlans200ResponsePlansValue';
import ListPlans200ResponsePlansValueAnnualPrice from './model/ListPlans200ResponsePlansValueAnnualPrice';
import ListPlans200ResponsePlansValueApiKeys from './model/ListPlans200ResponsePlansValueApiKeys';
import ListPlans200ResponsePlansValueMonthlyPrice from './model/ListPlans200ResponsePlansValueMonthlyPrice';
import Plan from './model/Plan';
import PlanPrice from './model/PlanPrice';
import PlansResponse from './model/PlansResponse';
import RootStatus200Response from './model/RootStatus200Response';
import StartDatasetJobRequest from './model/StartDatasetJobRequest';
import UsageStats from './model/UsageStats';
import DatasetsApi from './api/DatasetsApi';
import HealthApi from './api/HealthApi';
import PlansApi from './api/PlansApi';
import UsageApi from './api/UsageApi';


/**
* Every_number_on_the_internet.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Qoery = require('index'); // See note below*.
* var xxxSvc = new Qoery.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Qoery.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Qoery.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Qoery.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.5.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiInfo model constructor.
     * @property {module:model/ApiInfo}
     */
    ApiInfo,

    /**
     * The EndpointUsage model constructor.
     * @property {module:model/EndpointUsage}
     */
    EndpointUsage,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The GetDatasetJobStatus200Response model constructor.
     * @property {module:model/GetDatasetJobStatus200Response}
     */
    GetDatasetJobStatus200Response,

    /**
     * The GetDatasetJobStatus200ResponseProgress model constructor.
     * @property {module:model/GetDatasetJobStatus200ResponseProgress}
     */
    GetDatasetJobStatus200ResponseProgress,

    /**
     * The GetUsageStats200Response model constructor.
     * @property {module:model/GetUsageStats200Response}
     */
    GetUsageStats200Response,

    /**
     * The GetUsageStats200ResponseEndpointBreakdownInner model constructor.
     * @property {module:model/GetUsageStats200ResponseEndpointBreakdownInner}
     */
    GetUsageStats200ResponseEndpointBreakdownInner,

    /**
     * The HealthResponse model constructor.
     * @property {module:model/HealthResponse}
     */
    HealthResponse,

    /**
     * The JobProgress model constructor.
     * @property {module:model/JobProgress}
     */
    JobProgress,

    /**
     * The JobStartRequest model constructor.
     * @property {module:model/JobStartRequest}
     */
    JobStartRequest,

    /**
     * The JobStartResponse model constructor.
     * @property {module:model/JobStartResponse}
     */
    JobStartResponse,

    /**
     * The JobStatus model constructor.
     * @property {module:model/JobStatus}
     */
    JobStatus,

    /**
     * The ListDatasetsOrStartJob200Response model constructor.
     * @property {module:model/ListDatasetsOrStartJob200Response}
     */
    ListDatasetsOrStartJob200Response,

    /**
     * The ListDatasetsOrStartJob200ResponseOneOf model constructor.
     * @property {module:model/ListDatasetsOrStartJob200ResponseOneOf}
     */
    ListDatasetsOrStartJob200ResponseOneOf,

    /**
     * The ListDatasetsOrStartJob200ResponseOneOf1 model constructor.
     * @property {module:model/ListDatasetsOrStartJob200ResponseOneOf1}
     */
    ListDatasetsOrStartJob200ResponseOneOf1,

    /**
     * The ListDatasetsOrStartJob400Response model constructor.
     * @property {module:model/ListDatasetsOrStartJob400Response}
     */
    ListDatasetsOrStartJob400Response,

    /**
     * The ListDatasetsOrStartJob429Response model constructor.
     * @property {module:model/ListDatasetsOrStartJob429Response}
     */
    ListDatasetsOrStartJob429Response,

    /**
     * The ListPlans200Response model constructor.
     * @property {module:model/ListPlans200Response}
     */
    ListPlans200Response,

    /**
     * The ListPlans200ResponsePlansValue model constructor.
     * @property {module:model/ListPlans200ResponsePlansValue}
     */
    ListPlans200ResponsePlansValue,

    /**
     * The ListPlans200ResponsePlansValueAnnualPrice model constructor.
     * @property {module:model/ListPlans200ResponsePlansValueAnnualPrice}
     */
    ListPlans200ResponsePlansValueAnnualPrice,

    /**
     * The ListPlans200ResponsePlansValueApiKeys model constructor.
     * @property {module:model/ListPlans200ResponsePlansValueApiKeys}
     */
    ListPlans200ResponsePlansValueApiKeys,

    /**
     * The ListPlans200ResponsePlansValueMonthlyPrice model constructor.
     * @property {module:model/ListPlans200ResponsePlansValueMonthlyPrice}
     */
    ListPlans200ResponsePlansValueMonthlyPrice,

    /**
     * The Plan model constructor.
     * @property {module:model/Plan}
     */
    Plan,

    /**
     * The PlanPrice model constructor.
     * @property {module:model/PlanPrice}
     */
    PlanPrice,

    /**
     * The PlansResponse model constructor.
     * @property {module:model/PlansResponse}
     */
    PlansResponse,

    /**
     * The RootStatus200Response model constructor.
     * @property {module:model/RootStatus200Response}
     */
    RootStatus200Response,

    /**
     * The StartDatasetJobRequest model constructor.
     * @property {module:model/StartDatasetJobRequest}
     */
    StartDatasetJobRequest,

    /**
     * The UsageStats model constructor.
     * @property {module:model/UsageStats}
     */
    UsageStats,

    /**
    * The DatasetsApi service constructor.
    * @property {module:api/DatasetsApi}
    */
    DatasetsApi,

    /**
    * The HealthApi service constructor.
    * @property {module:api/HealthApi}
    */
    HealthApi,

    /**
    * The PlansApi service constructor.
    * @property {module:api/PlansApi}
    */
    PlansApi,

    /**
    * The UsageApi service constructor.
    * @property {module:api/UsageApi}
    */
    UsageApi
};
