# coding: utf-8

# flake8: noqa
"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 

    The version of the OpenAPI document: 0.4.0
    Contact: samuel.tinnerholm@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from qoery.models.error_response import ErrorResponse
from qoery.models.health_get200_response import HealthGet200Response
from qoery.models.nl_query_request import NLQueryRequest
from qoery.models.plans_get200_response import PlansGet200Response
from qoery.models.plans_get200_response_plans_value import PlansGet200ResponsePlansValue
from qoery.models.plans_get200_response_plans_value_api_keys import PlansGet200ResponsePlansValueApiKeys
from qoery.models.plans_get200_response_plans_value_monthly_price import PlansGet200ResponsePlansValueMonthlyPrice
from qoery.models.query_nl_get200_response import QueryNlGet200Response
from qoery.models.query_nl_get200_response_meta import QueryNlGet200ResponseMeta
from qoery.models.query_nl_get200_response_meta_page import QueryNlGet200ResponseMetaPage
from qoery.models.query_nl_get200_response_series_inner import QueryNlGet200ResponseSeriesInner
from qoery.models.query_nl_get200_response_series_inner_observations_inner import QueryNlGet200ResponseSeriesInnerObservationsInner
from qoery.models.query_nl_get200_response_series_inner_observations_inner_value import QueryNlGet200ResponseSeriesInnerObservationsInnerValue
from qoery.models.query_nl_get400_response import QueryNlGet400Response
from qoery.models.query_response import QueryResponse
from qoery.models.scrape_get200_response import ScrapeGet200Response
from qoery.models.scrape_get200_response_artifacts import ScrapeGet200ResponseArtifacts
from qoery.models.scrape_get200_response_metadata import ScrapeGet200ResponseMetadata
from qoery.models.scrape_response import ScrapeResponse
from qoery.models.url_request import URLRequest
from qoery.models.usage_get200_response import UsageGet200Response
from qoery.models.usage_get200_response_endpoints import UsageGet200ResponseEndpoints
from qoery.models.usage_get200_response_endpoints_nl import UsageGet200ResponseEndpointsNl
from qoery.models.usage_stats import UsageStats
