# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 

    The version of the OpenAPI document: 0.3.2
    Contact: samuel.tinnerholm@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from qoery.models.query_nl_get200_response_series_inner_observations_inner import QueryNlGet200ResponseSeriesInnerObservationsInner
from typing import Optional, Set
from typing_extensions import Self

class QueryNlGet200ResponseSeriesInner(BaseModel):
    """
    A data series with observations from a specific source
    """ # noqa: E501
    url: StrictStr = Field(description="URL of the source page")
    title: StrictStr = Field(description="Title of the series")
    url_title: StrictStr = Field(description="Title from the URL/source")
    observations: List[QueryNlGet200ResponseSeriesInnerObservationsInner] = Field(description="The ordered observations for this series")
    relevance_score: Union[StrictFloat, StrictInt] = Field(description="Relevance score for this series (0-1)")
    __properties: ClassVar[List[str]] = ["url", "title", "url_title", "observations", "relevance_score"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryNlGet200ResponseSeriesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in observations (list)
        _items = []
        if self.observations:
            for _item_observations in self.observations:
                if _item_observations:
                    _items.append(_item_observations.to_dict())
            _dict['observations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryNlGet200ResponseSeriesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "title": obj.get("title"),
            "url_title": obj.get("url_title"),
            "observations": [QueryNlGet200ResponseSeriesInnerObservationsInner.from_dict(_item) for _item in obj["observations"]] if obj.get("observations") is not None else None,
            "relevance_score": obj.get("relevance_score")
        })
        return _obj


