/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetDatasetJobStatus200ResponseProgress from './GetDatasetJobStatus200ResponseProgress';

/**
 * The JobStatus model module.
 * @module model/JobStatus
 * @version 0.5.0
 */
class JobStatus {
    /**
     * Constructs a new <code>JobStatus</code>.
     * Complete status information for a dataset collection job
     * @alias module:model/JobStatus
     * @param jobId {String} Unique identifier for the job
     * @param status {module:model/JobStatus.StatusEnum} Current job status. Possible values: - `processing`: Job is actively collecting and processing data - `completed`: Job finished successfully, CSV is ready for download - `error`: Job failed, check the `error` field for details 
     * @param query {String} Original search query
     * @param progress {module:model/GetDatasetJobStatus200ResponseProgress} 
     * @param urls {Array.<String>} List of URLs being processed
     * @param csvUrl {String} URL to download the CSV file
     * @param error {String} Error message if status is 'error'
     * @param startedAt {Date} Timestamp when the job started
     * @param completedAt {Date} Timestamp when the job completed (null if still processing)
     */
    constructor(jobId, status, query, progress, urls, csvUrl, error, startedAt, completedAt) { 
        
        JobStatus.initialize(this, jobId, status, query, progress, urls, csvUrl, error, startedAt, completedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jobId, status, query, progress, urls, csvUrl, error, startedAt, completedAt) { 
        obj['job_id'] = jobId;
        obj['status'] = status;
        obj['query'] = query;
        obj['progress'] = progress;
        obj['urls'] = urls;
        obj['csv_url'] = csvUrl;
        obj['error'] = error;
        obj['started_at'] = startedAt;
        obj['completed_at'] = completedAt;
    }

    /**
     * Constructs a <code>JobStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobStatus} obj Optional instance to populate.
     * @return {module:model/JobStatus} The populated <code>JobStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobStatus();

            if (data.hasOwnProperty('job_id')) {
                obj['job_id'] = ApiClient.convertToType(data['job_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('progress')) {
                obj['progress'] = GetDatasetJobStatus200ResponseProgress.constructFromObject(data['progress']);
            }
            if (data.hasOwnProperty('urls')) {
                obj['urls'] = ApiClient.convertToType(data['urls'], ['String']);
            }
            if (data.hasOwnProperty('csv_url')) {
                obj['csv_url'] = ApiClient.convertToType(data['csv_url'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Date');
            }
            if (data.hasOwnProperty('completed_at')) {
                obj['completed_at'] = ApiClient.convertToType(data['completed_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobStatus</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JobStatus.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['job_id'] && !(typeof data['job_id'] === 'string' || data['job_id'] instanceof String)) {
            throw new Error("Expected the field `job_id` to be a primitive type in the JSON string but got " + data['job_id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['query'] && !(typeof data['query'] === 'string' || data['query'] instanceof String)) {
            throw new Error("Expected the field `query` to be a primitive type in the JSON string but got " + data['query']);
        }
        // validate the optional field `progress`
        if (data['progress']) { // data not null
          GetDatasetJobStatus200ResponseProgress.validateJSON(data['progress']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['urls'])) {
            throw new Error("Expected the field `urls` to be an array in the JSON data but got " + data['urls']);
        }
        // ensure the json data is a string
        if (data['csv_url'] && !(typeof data['csv_url'] === 'string' || data['csv_url'] instanceof String)) {
            throw new Error("Expected the field `csv_url` to be a primitive type in the JSON string but got " + data['csv_url']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}

JobStatus.RequiredProperties = ["job_id", "status", "query", "progress", "urls", "csv_url", "error", "started_at", "completed_at"];

/**
 * Unique identifier for the job
 * @member {String} job_id
 */
JobStatus.prototype['job_id'] = undefined;

/**
 * Current job status. Possible values: - `processing`: Job is actively collecting and processing data - `completed`: Job finished successfully, CSV is ready for download - `error`: Job failed, check the `error` field for details 
 * @member {module:model/JobStatus.StatusEnum} status
 */
JobStatus.prototype['status'] = undefined;

/**
 * Original search query
 * @member {String} query
 */
JobStatus.prototype['query'] = undefined;

/**
 * @member {module:model/GetDatasetJobStatus200ResponseProgress} progress
 */
JobStatus.prototype['progress'] = undefined;

/**
 * List of URLs being processed
 * @member {Array.<String>} urls
 */
JobStatus.prototype['urls'] = undefined;

/**
 * URL to download the CSV file
 * @member {String} csv_url
 */
JobStatus.prototype['csv_url'] = undefined;

/**
 * Error message if status is 'error'
 * @member {String} error
 */
JobStatus.prototype['error'] = undefined;

/**
 * Timestamp when the job started
 * @member {Date} started_at
 */
JobStatus.prototype['started_at'] = undefined;

/**
 * Timestamp when the job completed (null if still processing)
 * @member {Date} completed_at
 */
JobStatus.prototype['completed_at'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
JobStatus['StatusEnum'] = {

    /**
     * value: "processing"
     * @const
     */
    "processing": "processing",

    /**
     * value: "completed"
     * @const
     */
    "completed": "completed",

    /**
     * value: "error"
     * @const
     */
    "error": "error"
};



export default JobStatus;

