/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobStartResponse model module.
 * @module model/JobStartResponse
 * @version 0.5.0
 */
class JobStartResponse {
    /**
     * Constructs a new <code>JobStartResponse</code>.
     * Response when a job is started
     * @alias module:model/JobStartResponse
     * @param jobId {String} Unique identifier for the job
     * @param status {module:model/JobStartResponse.StatusEnum} Initial job status
     * @param pollingIntervalMs {Number} Recommended polling interval in milliseconds
     */
    constructor(jobId, status, pollingIntervalMs) { 
        
        JobStartResponse.initialize(this, jobId, status, pollingIntervalMs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jobId, status, pollingIntervalMs) { 
        obj['job_id'] = jobId;
        obj['status'] = status;
        obj['polling_interval_ms'] = pollingIntervalMs;
    }

    /**
     * Constructs a <code>JobStartResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobStartResponse} obj Optional instance to populate.
     * @return {module:model/JobStartResponse} The populated <code>JobStartResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobStartResponse();

            if (data.hasOwnProperty('job_id')) {
                obj['job_id'] = ApiClient.convertToType(data['job_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('polling_interval_ms')) {
                obj['polling_interval_ms'] = ApiClient.convertToType(data['polling_interval_ms'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobStartResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobStartResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JobStartResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['job_id'] && !(typeof data['job_id'] === 'string' || data['job_id'] instanceof String)) {
            throw new Error("Expected the field `job_id` to be a primitive type in the JSON string but got " + data['job_id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

JobStartResponse.RequiredProperties = ["job_id", "status", "polling_interval_ms"];

/**
 * Unique identifier for the job
 * @member {String} job_id
 */
JobStartResponse.prototype['job_id'] = undefined;

/**
 * Initial job status
 * @member {module:model/JobStartResponse.StatusEnum} status
 */
JobStartResponse.prototype['status'] = undefined;

/**
 * Recommended polling interval in milliseconds
 * @member {Number} polling_interval_ms
 */
JobStartResponse.prototype['polling_interval_ms'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
JobStartResponse['StatusEnum'] = {

    /**
     * value: "processing"
     * @const
     */
    "processing": "processing"
};



export default JobStartResponse;

