/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListPlans200ResponsePlansValueMonthlyPrice model module.
 * @module model/ListPlans200ResponsePlansValueMonthlyPrice
 * @version 0.5.0
 */
class ListPlans200ResponsePlansValueMonthlyPrice {
    /**
     * Constructs a new <code>ListPlans200ResponsePlansValueMonthlyPrice</code>.
     * Monthly pricing option
     * @alias module:model/ListPlans200ResponsePlansValueMonthlyPrice
     * @param amount {Number} Price amount
     * @param currency {String} Currency code
     * @param priceId {String} Stripe price ID
     */
    constructor(amount, currency, priceId) { 
        
        ListPlans200ResponsePlansValueMonthlyPrice.initialize(this, amount, currency, priceId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, currency, priceId) { 
        obj['amount'] = amount;
        obj['currency'] = currency;
        obj['priceId'] = priceId;
    }

    /**
     * Constructs a <code>ListPlans200ResponsePlansValueMonthlyPrice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListPlans200ResponsePlansValueMonthlyPrice} obj Optional instance to populate.
     * @return {module:model/ListPlans200ResponsePlansValueMonthlyPrice} The populated <code>ListPlans200ResponsePlansValueMonthlyPrice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListPlans200ResponsePlansValueMonthlyPrice();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('priceId')) {
                obj['priceId'] = ApiClient.convertToType(data['priceId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListPlans200ResponsePlansValueMonthlyPrice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListPlans200ResponsePlansValueMonthlyPrice</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListPlans200ResponsePlansValueMonthlyPrice.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['priceId'] && !(typeof data['priceId'] === 'string' || data['priceId'] instanceof String)) {
            throw new Error("Expected the field `priceId` to be a primitive type in the JSON string but got " + data['priceId']);
        }

        return true;
    }


}

ListPlans200ResponsePlansValueMonthlyPrice.RequiredProperties = ["amount", "currency", "priceId"];

/**
 * Price amount
 * @member {Number} amount
 */
ListPlans200ResponsePlansValueMonthlyPrice.prototype['amount'] = undefined;

/**
 * Currency code
 * @member {String} currency
 */
ListPlans200ResponsePlansValueMonthlyPrice.prototype['currency'] = undefined;

/**
 * Stripe price ID
 * @member {String} priceId
 */
ListPlans200ResponsePlansValueMonthlyPrice.prototype['priceId'] = undefined;






export default ListPlans200ResponsePlansValueMonthlyPrice;

