/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryNlPost200ResponseSeriesInner from './QueryNlPost200ResponseSeriesInner';
import QuerySqlPost200ResponseMetadata from './QuerySqlPost200ResponseMetadata';

/**
 * The QuerySqlPost200Response model module.
 * @module model/QuerySqlPost200Response
 * @version 0.1.0
 */
class QuerySqlPost200Response {
    /**
     * Constructs a new <code>QuerySqlPost200Response</code>.
     * Response from SQL query endpoint
     * @alias module:model/QuerySqlPost200Response
     * @param series {Array.<module:model/QueryNlPost200ResponseSeriesInner>} Array of observations (flat structure, not nested)
     */
    constructor(series) { 
        
        QuerySqlPost200Response.initialize(this, series);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, series) { 
        obj['series'] = series;
    }

    /**
     * Constructs a <code>QuerySqlPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuerySqlPost200Response} obj Optional instance to populate.
     * @return {module:model/QuerySqlPost200Response} The populated <code>QuerySqlPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuerySqlPost200Response();

            if (data.hasOwnProperty('series')) {
                obj['series'] = ApiClient.convertToType(data['series'], [QueryNlPost200ResponseSeriesInner]);
            }
            if (data.hasOwnProperty('sql_query')) {
                obj['sql_query'] = ApiClient.convertToType(data['sql_query'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = QuerySqlPost200ResponseMetadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuerySqlPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuerySqlPost200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuerySqlPost200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['series']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['series'])) {
                throw new Error("Expected the field `series` to be an array in the JSON data but got " + data['series']);
            }
            // validate the optional field `series` (array)
            for (const item of data['series']) {
                QueryNlPost200ResponseSeriesInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['sql_query'] && !(typeof data['sql_query'] === 'string' || data['sql_query'] instanceof String)) {
            throw new Error("Expected the field `sql_query` to be a primitive type in the JSON string but got " + data['sql_query']);
        }

        return true;
    }


}

QuerySqlPost200Response.RequiredProperties = ["series"];

/**
 * Array of observations (flat structure, not nested)
 * @member {Array.<module:model/QueryNlPost200ResponseSeriesInner>} series
 */
QuerySqlPost200Response.prototype['series'] = undefined;

/**
 * The SQL query that was executed
 * @member {String} sql_query
 */
QuerySqlPost200Response.prototype['sql_query'] = undefined;

/**
 * @member {module:model/QuerySqlPost200ResponseMetadata} metadata
 */
QuerySqlPost200Response.prototype['metadata'] = undefined;






export default QuerySqlPost200Response;

