/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.3.2
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryNlGet200ResponseMetaPage from './QueryNlGet200ResponseMetaPage';

/**
 * The QueryNlGet200ResponseMeta model module.
 * @module model/QueryNlGet200ResponseMeta
 * @version 0.3.2
 */
class QueryNlGet200ResponseMeta {
    /**
     * Constructs a new <code>QueryNlGet200ResponseMeta</code>.
     * Metadata about query execution and pagination
     * @alias module:model/QueryNlGet200ResponseMeta
     * @param resultCount {Number} Number of results returned in this response
     */
    constructor(resultCount) { 
        
        QueryNlGet200ResponseMeta.initialize(this, resultCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, resultCount) { 
        obj['result_count'] = resultCount;
    }

    /**
     * Constructs a <code>QueryNlGet200ResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryNlGet200ResponseMeta} obj Optional instance to populate.
     * @return {module:model/QueryNlGet200ResponseMeta} The populated <code>QueryNlGet200ResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryNlGet200ResponseMeta();

            if (data.hasOwnProperty('result_count')) {
                obj['result_count'] = ApiClient.convertToType(data['result_count'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = QueryNlGet200ResponseMetaPage.constructFromObject(data['page']);
            }
            if (data.hasOwnProperty('diagnostics')) {
                obj['diagnostics'] = ApiClient.convertToType(data['diagnostics'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueryNlGet200ResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueryNlGet200ResponseMeta</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QueryNlGet200ResponseMeta.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `page`
        if (data['page']) { // data not null
          QueryNlGet200ResponseMetaPage.validateJSON(data['page']);
        }

        return true;
    }


}

QueryNlGet200ResponseMeta.RequiredProperties = ["result_count"];

/**
 * Number of results returned in this response
 * @member {Number} result_count
 */
QueryNlGet200ResponseMeta.prototype['result_count'] = undefined;

/**
 * @member {module:model/QueryNlGet200ResponseMetaPage} page
 */
QueryNlGet200ResponseMeta.prototype['page'] = undefined;

/**
 * Additional diagnostic information about the query execution
 * @member {Object.<String, Object>} diagnostics
 */
QueryNlGet200ResponseMeta.prototype['diagnostics'] = undefined;






export default QueryNlGet200ResponseMeta;

