/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueryNlGet200ResponseSeriesInnerUnit model module.
 * @module model/QueryNlGet200ResponseSeriesInnerUnit
 * @version 0.2.0
 */
class QueryNlGet200ResponseSeriesInnerUnit {
    /**
     * Constructs a new <code>QueryNlGet200ResponseSeriesInnerUnit</code>.
     * The unit used for the observation value
     * @alias module:model/QueryNlGet200ResponseSeriesInnerUnit
     * @param name {String} Human-readable name of the unit
     */
    constructor(name) { 
        
        QueryNlGet200ResponseSeriesInnerUnit.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>QueryNlGet200ResponseSeriesInnerUnit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryNlGet200ResponseSeriesInnerUnit} obj Optional instance to populate.
     * @return {module:model/QueryNlGet200ResponseSeriesInnerUnit} The populated <code>QueryNlGet200ResponseSeriesInnerUnit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryNlGet200ResponseSeriesInnerUnit();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueryNlGet200ResponseSeriesInnerUnit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueryNlGet200ResponseSeriesInnerUnit</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QueryNlGet200ResponseSeriesInnerUnit.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }

        return true;
    }


}

QueryNlGet200ResponseSeriesInnerUnit.RequiredProperties = ["name"];

/**
 * ID of the unit
 * @member {String} id
 */
QueryNlGet200ResponseSeriesInnerUnit.prototype['id'] = undefined;

/**
 * Human-readable name of the unit
 * @member {String} name
 */
QueryNlGet200ResponseSeriesInnerUnit.prototype['name'] = undefined;

/**
 * Symbol of the unit (e.g., $, %, kg)
 * @member {String} symbol
 */
QueryNlGet200ResponseSeriesInnerUnit.prototype['symbol'] = undefined;






export default QueryNlGet200ResponseSeriesInnerUnit;

