/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryNlGet200ResponseSeriesInnerObservationsInner from './QueryNlGet200ResponseSeriesInnerObservationsInner';

/**
 * The QueryNlGet200ResponseSeriesInner model module.
 * @module model/QueryNlGet200ResponseSeriesInner
 * @version 0.4.0
 */
class QueryNlGet200ResponseSeriesInner {
    /**
     * Constructs a new <code>QueryNlGet200ResponseSeriesInner</code>.
     * A data series with observations from a specific source
     * @alias module:model/QueryNlGet200ResponseSeriesInner
     * @param url {String} URL of the source page
     * @param title {String} Title of the series
     * @param urlTitle {String} Title from the URL/source
     * @param observations {Array.<module:model/QueryNlGet200ResponseSeriesInnerObservationsInner>} The ordered observations for this series
     * @param relevanceScore {Number} Relevance score for this series (0-1)
     */
    constructor(url, title, urlTitle, observations, relevanceScore) { 
        
        QueryNlGet200ResponseSeriesInner.initialize(this, url, title, urlTitle, observations, relevanceScore);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, title, urlTitle, observations, relevanceScore) { 
        obj['url'] = url;
        obj['title'] = title;
        obj['url_title'] = urlTitle;
        obj['observations'] = observations;
        obj['relevance_score'] = relevanceScore;
    }

    /**
     * Constructs a <code>QueryNlGet200ResponseSeriesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryNlGet200ResponseSeriesInner} obj Optional instance to populate.
     * @return {module:model/QueryNlGet200ResponseSeriesInner} The populated <code>QueryNlGet200ResponseSeriesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryNlGet200ResponseSeriesInner();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('url_title')) {
                obj['url_title'] = ApiClient.convertToType(data['url_title'], 'String');
            }
            if (data.hasOwnProperty('observations')) {
                obj['observations'] = ApiClient.convertToType(data['observations'], [QueryNlGet200ResponseSeriesInnerObservationsInner]);
            }
            if (data.hasOwnProperty('relevance_score')) {
                obj['relevance_score'] = ApiClient.convertToType(data['relevance_score'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueryNlGet200ResponseSeriesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueryNlGet200ResponseSeriesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QueryNlGet200ResponseSeriesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['url_title'] && !(typeof data['url_title'] === 'string' || data['url_title'] instanceof String)) {
            throw new Error("Expected the field `url_title` to be a primitive type in the JSON string but got " + data['url_title']);
        }
        if (data['observations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['observations'])) {
                throw new Error("Expected the field `observations` to be an array in the JSON data but got " + data['observations']);
            }
            // validate the optional field `observations` (array)
            for (const item of data['observations']) {
                QueryNlGet200ResponseSeriesInnerObservationsInner.validateJSON(item);
            };
        }

        return true;
    }


}

QueryNlGet200ResponseSeriesInner.RequiredProperties = ["url", "title", "url_title", "observations", "relevance_score"];

/**
 * URL of the source page
 * @member {String} url
 */
QueryNlGet200ResponseSeriesInner.prototype['url'] = undefined;

/**
 * Title of the series
 * @member {String} title
 */
QueryNlGet200ResponseSeriesInner.prototype['title'] = undefined;

/**
 * Title from the URL/source
 * @member {String} url_title
 */
QueryNlGet200ResponseSeriesInner.prototype['url_title'] = undefined;

/**
 * The ordered observations for this series
 * @member {Array.<module:model/QueryNlGet200ResponseSeriesInnerObservationsInner>} observations
 */
QueryNlGet200ResponseSeriesInner.prototype['observations'] = undefined;

/**
 * Relevance score for this series (0-1)
 * @member {Number} relevance_score
 */
QueryNlGet200ResponseSeriesInner.prototype['relevance_score'] = undefined;






export default QueryNlGet200ResponseSeriesInner;

