/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueryNlGet200ResponseSeriesInnerObservationsInnerValue model module.
 * @module model/QueryNlGet200ResponseSeriesInnerObservationsInnerValue
 * @version 0.3.0
 */
class QueryNlGet200ResponseSeriesInnerObservationsInnerValue {
    /**
     * Constructs a new <code>QueryNlGet200ResponseSeriesInnerObservationsInnerValue</code>.
     * Value of the observation
     * @alias module:model/QueryNlGet200ResponseSeriesInnerObservationsInnerValue
     * @param {(module:model/Boolean|module:model/Number|module:model/String)} instance The actual instance to initialize QueryNlGet200ResponseSeriesInnerObservationsInnerValue.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate number
            if (!(typeof instance === 'number' && instance % 1 != 0)) {
                throw new Error("Invalid value. Must be number. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Number
            errorMessages.push("Failed to construct Number: " + err)
        }

        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        try {
            // validate boolean
            if (!(typeof instance === 'boolean')) {
                throw new Error("Invalid value. Must be boolean. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Boolean
            errorMessages.push("Failed to construct Boolean: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `QueryNlGet200ResponseSeriesInnerObservationsInnerValue` with oneOf schemas Boolean, Number, String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `QueryNlGet200ResponseSeriesInnerObservationsInnerValue` with oneOf schemas Boolean, Number, String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>QueryNlGet200ResponseSeriesInnerObservationsInnerValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryNlGet200ResponseSeriesInnerObservationsInnerValue} obj Optional instance to populate.
     * @return {module:model/QueryNlGet200ResponseSeriesInnerObservationsInnerValue} The populated <code>QueryNlGet200ResponseSeriesInnerObservationsInnerValue</code> instance.
     */
    static constructFromObject(data, obj) {
        return new QueryNlGet200ResponseSeriesInnerObservationsInnerValue(data);
    }

    /**
     * Gets the actual instance, which can be <code>Boolean</code>, <code>Number</code>, <code>String</code>.
     * @return {(module:model/Boolean|module:model/Number|module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Boolean</code>, <code>Number</code>, <code>String</code>.
     * @param {(module:model/Boolean|module:model/Number|module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = QueryNlGet200ResponseSeriesInnerObservationsInnerValue.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of QueryNlGet200ResponseSeriesInnerObservationsInnerValue from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/QueryNlGet200ResponseSeriesInnerObservationsInnerValue} An instance of QueryNlGet200ResponseSeriesInnerObservationsInnerValue.
     */
    static fromJSON = function(json_string){
        return QueryNlGet200ResponseSeriesInnerObservationsInnerValue.constructFromObject(JSON.parse(json_string));
    }
}


QueryNlGet200ResponseSeriesInnerObservationsInnerValue.OneOf = ["Boolean", "Number", "String"];

export default QueryNlGet200ResponseSeriesInnerObservationsInnerValue;

