/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueryNlPost200ResponseMetaPage model module.
 * @module model/QueryNlPost200ResponseMetaPage
 * @version 0.2.0
 */
class QueryNlPost200ResponseMetaPage {
    /**
     * Constructs a new <code>QueryNlPost200ResponseMetaPage</code>.
     * Pagination information for the response
     * @alias module:model/QueryNlPost200ResponseMetaPage
     * @param limit {Number} Number of items requested per page
     * @param offset {Number} Offset index of the first item in this page
     * @param hasMore {Boolean} Whether there are more items available beyond this page
     */
    constructor(limit, offset, hasMore) { 
        
        QueryNlPost200ResponseMetaPage.initialize(this, limit, offset, hasMore);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, limit, offset, hasMore) { 
        obj['limit'] = limit;
        obj['offset'] = offset;
        obj['has_more'] = hasMore;
    }

    /**
     * Constructs a <code>QueryNlPost200ResponseMetaPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryNlPost200ResponseMetaPage} obj Optional instance to populate.
     * @return {module:model/QueryNlPost200ResponseMetaPage} The populated <code>QueryNlPost200ResponseMetaPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryNlPost200ResponseMetaPage();

            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('next_cursor')) {
                obj['next_cursor'] = ApiClient.convertToType(data['next_cursor'], 'String');
            }
            if (data.hasOwnProperty('has_more')) {
                obj['has_more'] = ApiClient.convertToType(data['has_more'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueryNlPost200ResponseMetaPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueryNlPost200ResponseMetaPage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QueryNlPost200ResponseMetaPage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['next_cursor'] && !(typeof data['next_cursor'] === 'string' || data['next_cursor'] instanceof String)) {
            throw new Error("Expected the field `next_cursor` to be a primitive type in the JSON string but got " + data['next_cursor']);
        }

        return true;
    }


}

QueryNlPost200ResponseMetaPage.RequiredProperties = ["limit", "offset", "has_more"];

/**
 * Number of items requested per page
 * @member {Number} limit
 */
QueryNlPost200ResponseMetaPage.prototype['limit'] = undefined;

/**
 * Offset index of the first item in this page
 * @member {Number} offset
 */
QueryNlPost200ResponseMetaPage.prototype['offset'] = undefined;

/**
 * Opaque token to fetch the next page
 * @member {String} next_cursor
 */
QueryNlPost200ResponseMetaPage.prototype['next_cursor'] = undefined;

/**
 * Whether there are more items available beyond this page
 * @member {Boolean} has_more
 */
QueryNlPost200ResponseMetaPage.prototype['has_more'] = undefined;






export default QueryNlPost200ResponseMetaPage;

