/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuerySqlPost200ResponseMetadata model module.
 * @module model/QuerySqlPost200ResponseMetadata
 * @version 0.1.0
 */
class QuerySqlPost200ResponseMetadata {
    /**
     * Constructs a new <code>QuerySqlPost200ResponseMetadata</code>.
     * Metadata about query execution
     * @alias module:model/QuerySqlPost200ResponseMetadata
     * @extends Object
     */
    constructor() { 
        
        QuerySqlPost200ResponseMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QuerySqlPost200ResponseMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuerySqlPost200ResponseMetadata} obj Optional instance to populate.
     * @return {module:model/QuerySqlPost200ResponseMetadata} The populated <code>QuerySqlPost200ResponseMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuerySqlPost200ResponseMetadata();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('result_count')) {
                obj['result_count'] = ApiClient.convertToType(data['result_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuerySqlPost200ResponseMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuerySqlPost200ResponseMetadata</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Number of results returned
 * @member {Number} result_count
 */
QuerySqlPost200ResponseMetadata.prototype['result_count'] = undefined;






export default QuerySqlPost200ResponseMetadata;

