/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryNlGet200ResponseAllOfSeriesInner from './QueryNlGet200ResponseAllOfSeriesInner';

/**
 * The QueryNlGet200Response model module.
 * @module model/QueryNlGet200Response
 * @version 0.1.0
 */
class QueryNlGet200Response {
    /**
     * Constructs a new <code>QueryNlGet200Response</code>.
     * @alias module:model/QueryNlGet200Response
     * @param series {Array.<module:model/QueryNlGet200ResponseAllOfSeriesInner>} 
     * @param sqlQuery {String} The generated SQL query
     */
    constructor(series, sqlQuery) { 
        
        QueryNlGet200Response.initialize(this, series, sqlQuery);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, series, sqlQuery) { 
        obj['series'] = series;
        obj['sql_query'] = sqlQuery;
    }

    /**
     * Constructs a <code>QueryNlGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryNlGet200Response} obj Optional instance to populate.
     * @return {module:model/QueryNlGet200Response} The populated <code>QueryNlGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryNlGet200Response();

            if (data.hasOwnProperty('series')) {
                obj['series'] = ApiClient.convertToType(data['series'], [QueryNlGet200ResponseAllOfSeriesInner]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': Object});
            }
            if (data.hasOwnProperty('sql_query')) {
                obj['sql_query'] = ApiClient.convertToType(data['sql_query'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueryNlGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueryNlGet200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QueryNlGet200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['series']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['series'])) {
                throw new Error("Expected the field `series` to be an array in the JSON data but got " + data['series']);
            }
            // validate the optional field `series` (array)
            for (const item of data['series']) {
                QueryNlGet200ResponseAllOfSeriesInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['sql_query'] && !(typeof data['sql_query'] === 'string' || data['sql_query'] instanceof String)) {
            throw new Error("Expected the field `sql_query` to be a primitive type in the JSON string but got " + data['sql_query']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

QueryNlGet200Response.RequiredProperties = ["series", "sql_query"];

/**
 * @member {Array.<module:model/QueryNlGet200ResponseAllOfSeriesInner>} series
 */
QueryNlGet200Response.prototype['series'] = undefined;

/**
 * Additional metadata about the query execution
 * @member {Object.<String, Object>} metadata
 */
QueryNlGet200Response.prototype['metadata'] = undefined;

/**
 * The generated SQL query
 * @member {String} sql_query
 */
QueryNlGet200Response.prototype['sql_query'] = undefined;

/**
 * Natural language description of the query result
 * @member {String} description
 */
QueryNlGet200Response.prototype['description'] = undefined;






export default QueryNlGet200Response;

