/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueryNlGet200ResponseSeriesInnerSource model module.
 * @module model/QueryNlGet200ResponseSeriesInnerSource
 * @version 0.2.0
 */
class QueryNlGet200ResponseSeriesInnerSource {
    /**
     * Constructs a new <code>QueryNlGet200ResponseSeriesInnerSource</code>.
     * Provenance record for a dataset or observation source
     * @alias module:model/QueryNlGet200ResponseSeriesInnerSource
     * @param id {Number} Numeric ID of the source in the database
     * @param url {String} Canonical URL of the data source
     */
    constructor(id, url) { 
        
        QueryNlGet200ResponseSeriesInnerSource.initialize(this, id, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, url) { 
        obj['id'] = id;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>QueryNlGet200ResponseSeriesInnerSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryNlGet200ResponseSeriesInnerSource} obj Optional instance to populate.
     * @return {module:model/QueryNlGet200ResponseSeriesInnerSource} The populated <code>QueryNlGet200ResponseSeriesInnerSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryNlGet200ResponseSeriesInnerSource();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueryNlGet200ResponseSeriesInnerSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueryNlGet200ResponseSeriesInnerSource</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QueryNlGet200ResponseSeriesInnerSource.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

QueryNlGet200ResponseSeriesInnerSource.RequiredProperties = ["id", "url"];

/**
 * Numeric ID of the source in the database
 * @member {Number} id
 */
QueryNlGet200ResponseSeriesInnerSource.prototype['id'] = undefined;

/**
 * Canonical URL of the data source
 * @member {String} url
 */
QueryNlGet200ResponseSeriesInnerSource.prototype['url'] = undefined;

/**
 * Human-readable description of the source
 * @member {String} description
 */
QueryNlGet200ResponseSeriesInnerSource.prototype['description'] = undefined;






export default QueryNlGet200ResponseSeriesInnerSource;

