/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryNlPost200ResponseSeriesInner from './QueryNlPost200ResponseSeriesInner';
import ScrapePost200ResponseArtifacts from './ScrapePost200ResponseArtifacts';
import ScrapePost200ResponseMetadata from './ScrapePost200ResponseMetadata';

/**
 * The ScrapePost200Response model module.
 * @module model/ScrapePost200Response
 * @version 0.1.0
 */
class ScrapePost200Response {
    /**
     * Constructs a new <code>ScrapePost200Response</code>.
     * Response from web scraping endpoint
     * @alias module:model/ScrapePost200Response
     * @param series {Array.<module:model/QueryNlPost200ResponseSeriesInner>} Array of observations extracted from the page (flat structure)
     */
    constructor(series) { 
        
        ScrapePost200Response.initialize(this, series);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, series) { 
        obj['series'] = series;
    }

    /**
     * Constructs a <code>ScrapePost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScrapePost200Response} obj Optional instance to populate.
     * @return {module:model/ScrapePost200Response} The populated <code>ScrapePost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScrapePost200Response();

            if (data.hasOwnProperty('series')) {
                obj['series'] = ApiClient.convertToType(data['series'], [QueryNlPost200ResponseSeriesInner]);
            }
            if (data.hasOwnProperty('artifacts')) {
                obj['artifacts'] = ScrapePost200ResponseArtifacts.constructFromObject(data['artifacts']);
            }
            if (data.hasOwnProperty('cached')) {
                obj['cached'] = ApiClient.convertToType(data['cached'], 'Boolean');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ScrapePost200ResponseMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
            if (data.hasOwnProperty('markdown')) {
                obj['markdown'] = ApiClient.convertToType(data['markdown'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScrapePost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScrapePost200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScrapePost200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['series']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['series'])) {
                throw new Error("Expected the field `series` to be an array in the JSON data but got " + data['series']);
            }
            // validate the optional field `series` (array)
            for (const item of data['series']) {
                QueryNlPost200ResponseSeriesInner.validateJSON(item);
            };
        }
        // validate the optional field `artifacts`
        if (data['artifacts']) { // data not null
          ScrapePost200ResponseArtifacts.validateJSON(data['artifacts']);
        }
        // ensure the json data is a string
        if (data['source_id'] && !(typeof data['source_id'] === 'string' || data['source_id'] instanceof String)) {
            throw new Error("Expected the field `source_id` to be a primitive type in the JSON string but got " + data['source_id']);
        }
        // ensure the json data is a string
        if (data['html'] && !(typeof data['html'] === 'string' || data['html'] instanceof String)) {
            throw new Error("Expected the field `html` to be a primitive type in the JSON string but got " + data['html']);
        }
        // ensure the json data is a string
        if (data['markdown'] && !(typeof data['markdown'] === 'string' || data['markdown'] instanceof String)) {
            throw new Error("Expected the field `markdown` to be a primitive type in the JSON string but got " + data['markdown']);
        }

        return true;
    }


}

ScrapePost200Response.RequiredProperties = ["series"];

/**
 * Array of observations extracted from the page (flat structure)
 * @member {Array.<module:model/QueryNlPost200ResponseSeriesInner>} series
 */
ScrapePost200Response.prototype['series'] = undefined;

/**
 * @member {module:model/ScrapePost200ResponseArtifacts} artifacts
 */
ScrapePost200Response.prototype['artifacts'] = undefined;

/**
 * Whether this result was retrieved from cache
 * @member {Boolean} cached
 */
ScrapePost200Response.prototype['cached'] = undefined;

/**
 * Database source ID (present when cached=true)
 * @member {String} source_id
 */
ScrapePost200Response.prototype['source_id'] = undefined;

/**
 * @member {module:model/ScrapePost200ResponseMetadata} metadata
 */
ScrapePost200Response.prototype['metadata'] = undefined;

/**
 * Original HTML of the page (only if html=true query param)
 * @member {String} html
 */
ScrapePost200Response.prototype['html'] = undefined;

/**
 * Markdown representation of the page (only if markdown=true query param)
 * @member {String} markdown
 */
ScrapePost200Response.prototype['markdown'] = undefined;






export default ScrapePost200Response;

