/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.3.2
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScrapeGet200ResponseMetadata model module.
 * @module model/ScrapeGet200ResponseMetadata
 * @version 0.3.2
 */
class ScrapeGet200ResponseMetadata {
    /**
     * Constructs a new <code>ScrapeGet200ResponseMetadata</code>.
     * Additional metadata about the scrape
     * @alias module:model/ScrapeGet200ResponseMetadata
     * @extends Object
     */
    constructor() { 
        
        ScrapeGet200ResponseMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScrapeGet200ResponseMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScrapeGet200ResponseMetadata} obj Optional instance to populate.
     * @return {module:model/ScrapeGet200ResponseMetadata} The populated <code>ScrapeGet200ResponseMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScrapeGet200ResponseMetadata();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('result_count')) {
                obj['result_count'] = ApiClient.convertToType(data['result_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScrapeGet200ResponseMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScrapeGet200ResponseMetadata</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Number of observations extracted
 * @member {Number} result_count
 */
ScrapeGet200ResponseMetadata.prototype['result_count'] = undefined;






export default ScrapeGet200ResponseMetadata;

