/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScrapePost200ResponseArtifacts model module.
 * @module model/ScrapePost200ResponseArtifacts
 * @version 0.1.0
 */
class ScrapePost200ResponseArtifacts {
    /**
     * Constructs a new <code>ScrapePost200ResponseArtifacts</code>.
     * URLs to stored artifacts for larger payloads
     * @alias module:model/ScrapePost200ResponseArtifacts
     */
    constructor() { 
        
        ScrapePost200ResponseArtifacts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScrapePost200ResponseArtifacts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScrapePost200ResponseArtifacts} obj Optional instance to populate.
     * @return {module:model/ScrapePost200ResponseArtifacts} The populated <code>ScrapePost200ResponseArtifacts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScrapePost200ResponseArtifacts();

            if (data.hasOwnProperty('html_url')) {
                obj['html_url'] = ApiClient.convertToType(data['html_url'], 'String');
            }
            if (data.hasOwnProperty('markdown_url')) {
                obj['markdown_url'] = ApiClient.convertToType(data['markdown_url'], 'String');
            }
            if (data.hasOwnProperty('tables_base_url')) {
                obj['tables_base_url'] = ApiClient.convertToType(data['tables_base_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScrapePost200ResponseArtifacts</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScrapePost200ResponseArtifacts</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['html_url'] && !(typeof data['html_url'] === 'string' || data['html_url'] instanceof String)) {
            throw new Error("Expected the field `html_url` to be a primitive type in the JSON string but got " + data['html_url']);
        }
        // ensure the json data is a string
        if (data['markdown_url'] && !(typeof data['markdown_url'] === 'string' || data['markdown_url'] instanceof String)) {
            throw new Error("Expected the field `markdown_url` to be a primitive type in the JSON string but got " + data['markdown_url']);
        }
        // ensure the json data is a string
        if (data['tables_base_url'] && !(typeof data['tables_base_url'] === 'string' || data['tables_base_url'] instanceof String)) {
            throw new Error("Expected the field `tables_base_url` to be a primitive type in the JSON string but got " + data['tables_base_url']);
        }

        return true;
    }


}



/**
 * @member {String} html_url
 */
ScrapePost200ResponseArtifacts.prototype['html_url'] = undefined;

/**
 * @member {String} markdown_url
 */
ScrapePost200ResponseArtifacts.prototype['markdown_url'] = undefined;

/**
 * @member {String} tables_base_url
 */
ScrapePost200ResponseArtifacts.prototype['tables_base_url'] = undefined;






export default ScrapePost200ResponseArtifacts;

