/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryNlGet200ResponseAllOfSeriesInner from './QueryNlGet200ResponseAllOfSeriesInner';
import QueryNlGet200ResponseAllOfSeriesInnerObservationsInner from './QueryNlGet200ResponseAllOfSeriesInnerObservationsInner';
import ScrapeGet200ResponseSeriesInnerOneOf from './ScrapeGet200ResponseSeriesInnerOneOf';

/**
 * The ScrapeGet200ResponseSeriesInner model module.
 * @module model/ScrapeGet200ResponseSeriesInner
 * @version 0.1.0
 */
class ScrapeGet200ResponseSeriesInner {
    /**
     * Constructs a new <code>ScrapeGet200ResponseSeriesInner</code>.
     * @alias module:model/ScrapeGet200ResponseSeriesInner
     * @param {(module:model/QueryNlGet200ResponseAllOfSeriesInner|module:model/ScrapeGet200ResponseSeriesInnerOneOf)} instance The actual instance to initialize ScrapeGet200ResponseSeriesInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "QueryNlGet200ResponseAllOfSeriesInner") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                QueryNlGet200ResponseAllOfSeriesInner.validateJSON(instance); // throw an exception if no match
                // create QueryNlGet200ResponseAllOfSeriesInner from JS object
                this.actualInstance = QueryNlGet200ResponseAllOfSeriesInner.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into QueryNlGet200ResponseAllOfSeriesInner
            errorMessages.push("Failed to construct QueryNlGet200ResponseAllOfSeriesInner: " + err)
        }

        try {
            if (typeof instance === "ScrapeGet200ResponseSeriesInnerOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ScrapeGet200ResponseSeriesInnerOneOf.validateJSON(instance); // throw an exception if no match
                // create ScrapeGet200ResponseSeriesInnerOneOf from JS object
                this.actualInstance = ScrapeGet200ResponseSeriesInnerOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ScrapeGet200ResponseSeriesInnerOneOf
            errorMessages.push("Failed to construct ScrapeGet200ResponseSeriesInnerOneOf: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `ScrapeGet200ResponseSeriesInner` with oneOf schemas QueryNlGet200ResponseAllOfSeriesInner, ScrapeGet200ResponseSeriesInnerOneOf. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `ScrapeGet200ResponseSeriesInner` with oneOf schemas QueryNlGet200ResponseAllOfSeriesInner, ScrapeGet200ResponseSeriesInnerOneOf. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>ScrapeGet200ResponseSeriesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScrapeGet200ResponseSeriesInner} obj Optional instance to populate.
     * @return {module:model/ScrapeGet200ResponseSeriesInner} The populated <code>ScrapeGet200ResponseSeriesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new ScrapeGet200ResponseSeriesInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>QueryNlGet200ResponseAllOfSeriesInner</code>, <code>ScrapeGet200ResponseSeriesInnerOneOf</code>.
     * @return {(module:model/QueryNlGet200ResponseAllOfSeriesInner|module:model/ScrapeGet200ResponseSeriesInnerOneOf)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>QueryNlGet200ResponseAllOfSeriesInner</code>, <code>ScrapeGet200ResponseSeriesInnerOneOf</code>.
     * @param {(module:model/QueryNlGet200ResponseAllOfSeriesInner|module:model/ScrapeGet200ResponseSeriesInnerOneOf)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = ScrapeGet200ResponseSeriesInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of ScrapeGet200ResponseSeriesInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/ScrapeGet200ResponseSeriesInner} An instance of ScrapeGet200ResponseSeriesInner.
     */
    static fromJSON = function(json_string){
        return ScrapeGet200ResponseSeriesInner.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * short id for the series (optional but recommended)
 * @member {String} series_id
 */
ScrapeGet200ResponseSeriesInner.prototype['series_id'] = undefined;

/**
 * human-friendly name for the series
 * @member {String} name
 */
ScrapeGet200ResponseSeriesInner.prototype['name'] = undefined;

/**
 * unit of measurement (optional)
 * @member {String} unit
 */
ScrapeGet200ResponseSeriesInner.prototype['unit'] = undefined;

/**
 * @member {Array.<module:model/QueryNlGet200ResponseAllOfSeriesInnerObservationsInner>} observations
 */
ScrapeGet200ResponseSeriesInner.prototype['observations'] = undefined;

/**
 * @member {Number} id
 */
ScrapeGet200ResponseSeriesInner.prototype['id'] = undefined;

/**
 * @member {Number} entity_id
 */
ScrapeGet200ResponseSeriesInner.prototype['entity_id'] = undefined;

/**
 * @member {Number} metric_id
 */
ScrapeGet200ResponseSeriesInner.prototype['metric_id'] = undefined;

/**
 * @member {Number} unit_id
 */
ScrapeGet200ResponseSeriesInner.prototype['unit_id'] = undefined;

/**
 * @member {String} frequency
 */
ScrapeGet200ResponseSeriesInner.prototype['frequency'] = undefined;

/**
 * @member {String} description
 */
ScrapeGet200ResponseSeriesInner.prototype['description'] = undefined;

/**
 * @member {Object.<String, Object>} labels
 */
ScrapeGet200ResponseSeriesInner.prototype['labels'] = undefined;

/**
 * @member {Number} observations_count
 */
ScrapeGet200ResponseSeriesInner.prototype['observations_count'] = undefined;


ScrapeGet200ResponseSeriesInner.OneOf = ["QueryNlGet200ResponseAllOfSeriesInner", "ScrapeGet200ResponseSeriesInnerOneOf"];

export default ScrapeGet200ResponseSeriesInner;

