/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SQLQueryRequest model module.
 * @module model/SQLQueryRequest
 * @version 0.1.0
 */
class SQLQueryRequest {
    /**
     * Constructs a new <code>SQLQueryRequest</code>.
     * @alias module:model/SQLQueryRequest
     * @param sqlQuery {String} 
     */
    constructor(sqlQuery) { 
        
        SQLQueryRequest.initialize(this, sqlQuery);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sqlQuery) { 
        obj['sql_query'] = sqlQuery;
    }

    /**
     * Constructs a <code>SQLQueryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SQLQueryRequest} obj Optional instance to populate.
     * @return {module:model/SQLQueryRequest} The populated <code>SQLQueryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SQLQueryRequest();

            if (data.hasOwnProperty('sql_query')) {
                obj['sql_query'] = ApiClient.convertToType(data['sql_query'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SQLQueryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SQLQueryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SQLQueryRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['sql_query'] && !(typeof data['sql_query'] === 'string' || data['sql_query'] instanceof String)) {
            throw new Error("Expected the field `sql_query` to be a primitive type in the JSON string but got " + data['sql_query']);
        }

        return true;
    }


}

SQLQueryRequest.RequiredProperties = ["sql_query"];

/**
 * @member {String} sql_query
 */
SQLQueryRequest.prototype['sql_query'] = undefined;






export default SQLQueryRequest;

