/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StartDatasetJobRequest model module.
 * @module model/StartDatasetJobRequest
 * @version 0.5.0
 */
class StartDatasetJobRequest {
    /**
     * Constructs a new <code>StartDatasetJobRequest</code>.
     * Request to start a new dataset collection job
     * @alias module:model/StartDatasetJobRequest
     * @param search {String} Search query for dataset collection
     */
    constructor(search) { 
        
        StartDatasetJobRequest.initialize(this, search);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, search) { 
        obj['search'] = search;
    }

    /**
     * Constructs a <code>StartDatasetJobRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StartDatasetJobRequest} obj Optional instance to populate.
     * @return {module:model/StartDatasetJobRequest} The populated <code>StartDatasetJobRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StartDatasetJobRequest();

            if (data.hasOwnProperty('search')) {
                obj['search'] = ApiClient.convertToType(data['search'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StartDatasetJobRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StartDatasetJobRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StartDatasetJobRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['search'] && !(typeof data['search'] === 'string' || data['search'] instanceof String)) {
            throw new Error("Expected the field `search` to be a primitive type in the JSON string but got " + data['search']);
        }

        return true;
    }


}

StartDatasetJobRequest.RequiredProperties = ["search"];

/**
 * Search query for dataset collection
 * @member {String} search
 */
StartDatasetJobRequest.prototype['search'] = undefined;






export default StartDatasetJobRequest;

