/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 
 *
 * The version of the OpenAPI document: 0.3.2
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsageStatsEndpointsNl from './UsageStatsEndpointsNl';

/**
 * The UsageStatsEndpoints model module.
 * @module model/UsageStatsEndpoints
 * @version 0.3.2
 */
class UsageStatsEndpoints {
    /**
     * Constructs a new <code>UsageStatsEndpoints</code>.
     * Usage statistics broken down by endpoint
     * @alias module:model/UsageStatsEndpoints
     * @param nl {module:model/UsageStatsEndpointsNl} 
     * @param scrape {module:model/UsageStatsEndpointsNl} 
     * @param plot2table {module:model/UsageStatsEndpointsNl} 
     */
    constructor(nl, scrape, plot2table) { 
        
        UsageStatsEndpoints.initialize(this, nl, scrape, plot2table);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nl, scrape, plot2table) { 
        obj['nl'] = nl;
        obj['scrape'] = scrape;
        obj['plot2table'] = plot2table;
    }

    /**
     * Constructs a <code>UsageStatsEndpoints</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsageStatsEndpoints} obj Optional instance to populate.
     * @return {module:model/UsageStatsEndpoints} The populated <code>UsageStatsEndpoints</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsageStatsEndpoints();

            if (data.hasOwnProperty('nl')) {
                obj['nl'] = UsageStatsEndpointsNl.constructFromObject(data['nl']);
            }
            if (data.hasOwnProperty('scrape')) {
                obj['scrape'] = UsageStatsEndpointsNl.constructFromObject(data['scrape']);
            }
            if (data.hasOwnProperty('plot2table')) {
                obj['plot2table'] = UsageStatsEndpointsNl.constructFromObject(data['plot2table']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsageStatsEndpoints</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsageStatsEndpoints</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UsageStatsEndpoints.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `nl`
        if (data['nl']) { // data not null
          UsageStatsEndpointsNl.validateJSON(data['nl']);
        }
        // validate the optional field `scrape`
        if (data['scrape']) { // data not null
          UsageStatsEndpointsNl.validateJSON(data['scrape']);
        }
        // validate the optional field `plot2table`
        if (data['plot2table']) { // data not null
          UsageStatsEndpointsNl.validateJSON(data['plot2table']);
        }

        return true;
    }


}

UsageStatsEndpoints.RequiredProperties = ["nl", "scrape", "plot2table"];

/**
 * @member {module:model/UsageStatsEndpointsNl} nl
 */
UsageStatsEndpoints.prototype['nl'] = undefined;

/**
 * @member {module:model/UsageStatsEndpointsNl} scrape
 */
UsageStatsEndpoints.prototype['scrape'] = undefined;

/**
 * @member {module:model/UsageStatsEndpointsNl} plot2table
 */
UsageStatsEndpoints.prototype['plot2table'] = undefined;






export default UsageStatsEndpoints;

