/**
 * qoery's API
 * Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsageGet200ResponseEndpoints from './UsageGet200ResponseEndpoints';

/**
 * The UsageStats model module.
 * @module model/UsageStats
 * @version 0.1.0
 */
class UsageStats {
    /**
     * Constructs a new <code>UsageStats</code>.
     * Usage statistics per endpoint
     * @alias module:model/UsageStats
     * @param periodStart {Date} Start of the current usage period
     * @param periodEnd {Date} End of the current usage period
     * @param plan {String} Current subscription plan
     * @param endpoints {module:model/UsageGet200ResponseEndpoints} 
     */
    constructor(periodStart, periodEnd, plan, endpoints) { 
        
        UsageStats.initialize(this, periodStart, periodEnd, plan, endpoints);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, periodStart, periodEnd, plan, endpoints) { 
        obj['period_start'] = periodStart;
        obj['period_end'] = periodEnd;
        obj['plan'] = plan;
        obj['endpoints'] = endpoints;
    }

    /**
     * Constructs a <code>UsageStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsageStats} obj Optional instance to populate.
     * @return {module:model/UsageStats} The populated <code>UsageStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsageStats();

            if (data.hasOwnProperty('period_start')) {
                obj['period_start'] = ApiClient.convertToType(data['period_start'], 'Date');
            }
            if (data.hasOwnProperty('period_end')) {
                obj['period_end'] = ApiClient.convertToType(data['period_end'], 'Date');
            }
            if (data.hasOwnProperty('plan')) {
                obj['plan'] = ApiClient.convertToType(data['plan'], 'String');
            }
            if (data.hasOwnProperty('endpoints')) {
                obj['endpoints'] = UsageGet200ResponseEndpoints.constructFromObject(data['endpoints']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsageStats</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsageStats</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UsageStats.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['plan'] && !(typeof data['plan'] === 'string' || data['plan'] instanceof String)) {
            throw new Error("Expected the field `plan` to be a primitive type in the JSON string but got " + data['plan']);
        }
        // validate the optional field `endpoints`
        if (data['endpoints']) { // data not null
          UsageGet200ResponseEndpoints.validateJSON(data['endpoints']);
        }

        return true;
    }


}

UsageStats.RequiredProperties = ["period_start", "period_end", "plan", "endpoints"];

/**
 * Start of the current usage period
 * @member {Date} period_start
 */
UsageStats.prototype['period_start'] = undefined;

/**
 * End of the current usage period
 * @member {Date} period_end
 */
UsageStats.prototype['period_end'] = undefined;

/**
 * Current subscription plan
 * @member {String} plan
 */
UsageStats.prototype['plan'] = undefined;

/**
 * @member {module:model/UsageGet200ResponseEndpoints} endpoints
 */
UsageStats.prototype['endpoints'] = undefined;






export default UsageStats;

