/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V0DatasetsGet400Response model module.
 * @module model/V0DatasetsGet400Response
 * @version 0.5.0
 */
class V0DatasetsGet400Response {
    /**
     * Constructs a new <code>V0DatasetsGet400Response</code>.
     * Standard error response
     * @alias module:model/V0DatasetsGet400Response
     * @param error {String} Error message
     * @param status {Number} HTTP status code
     */
    constructor(error, status) { 
        
        V0DatasetsGet400Response.initialize(this, error, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error, status) { 
        obj['error'] = error;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>V0DatasetsGet400Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V0DatasetsGet400Response} obj Optional instance to populate.
     * @return {module:model/V0DatasetsGet400Response} The populated <code>V0DatasetsGet400Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V0DatasetsGet400Response();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V0DatasetsGet400Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V0DatasetsGet400Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V0DatasetsGet400Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // ensure the json data is a string
        if (data['details'] && !(typeof data['details'] === 'string' || data['details'] instanceof String)) {
            throw new Error("Expected the field `details` to be a primitive type in the JSON string but got " + data['details']);
        }

        return true;
    }


}

V0DatasetsGet400Response.RequiredProperties = ["error", "status"];

/**
 * Error message
 * @member {String} error
 */
V0DatasetsGet400Response.prototype['error'] = undefined;

/**
 * HTTP status code
 * @member {Number} status
 */
V0DatasetsGet400Response.prototype['status'] = undefined;

/**
 * Additional error details
 * @member {String} details
 */
V0DatasetsGet400Response.prototype['details'] = undefined;






export default V0DatasetsGet400Response;

