/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V0DatasetsGet200ResponseOneOf from './V0DatasetsGet200ResponseOneOf';
import V0DatasetsGet200ResponseOneOf1 from './V0DatasetsGet200ResponseOneOf1';

/**
 * The V0DatasetsGet200Response model module.
 * @module model/V0DatasetsGet200Response
 * @version 0.5.0
 */
class V0DatasetsGet200Response {
    /**
     * Constructs a new <code>V0DatasetsGet200Response</code>.
     * @alias module:model/V0DatasetsGet200Response
     * @param {(module:model/V0DatasetsGet200ResponseOneOf|module:model/V0DatasetsGet200ResponseOneOf1)} instance The actual instance to initialize V0DatasetsGet200Response.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "V0DatasetsGet200ResponseOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                V0DatasetsGet200ResponseOneOf.validateJSON(instance); // throw an exception if no match
                // create V0DatasetsGet200ResponseOneOf from JS object
                this.actualInstance = V0DatasetsGet200ResponseOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into V0DatasetsGet200ResponseOneOf
            errorMessages.push("Failed to construct V0DatasetsGet200ResponseOneOf: " + err)
        }

        try {
            if (typeof instance === "V0DatasetsGet200ResponseOneOf1") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                V0DatasetsGet200ResponseOneOf1.validateJSON(instance); // throw an exception if no match
                // create V0DatasetsGet200ResponseOneOf1 from JS object
                this.actualInstance = V0DatasetsGet200ResponseOneOf1.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into V0DatasetsGet200ResponseOneOf1
            errorMessages.push("Failed to construct V0DatasetsGet200ResponseOneOf1: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `V0DatasetsGet200Response` with oneOf schemas V0DatasetsGet200ResponseOneOf, V0DatasetsGet200ResponseOneOf1. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `V0DatasetsGet200Response` with oneOf schemas V0DatasetsGet200ResponseOneOf, V0DatasetsGet200ResponseOneOf1. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>V0DatasetsGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V0DatasetsGet200Response} obj Optional instance to populate.
     * @return {module:model/V0DatasetsGet200Response} The populated <code>V0DatasetsGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        return new V0DatasetsGet200Response(data);
    }

    /**
     * Gets the actual instance, which can be <code>V0DatasetsGet200ResponseOneOf</code>, <code>V0DatasetsGet200ResponseOneOf1</code>.
     * @return {(module:model/V0DatasetsGet200ResponseOneOf|module:model/V0DatasetsGet200ResponseOneOf1)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>V0DatasetsGet200ResponseOneOf</code>, <code>V0DatasetsGet200ResponseOneOf1</code>.
     * @param {(module:model/V0DatasetsGet200ResponseOneOf|module:model/V0DatasetsGet200ResponseOneOf1)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = V0DatasetsGet200Response.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of V0DatasetsGet200Response from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/V0DatasetsGet200Response} An instance of V0DatasetsGet200Response.
     */
    static fromJSON = function(json_string){
        return V0DatasetsGet200Response.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} message
 */
V0DatasetsGet200Response.prototype['message'] = undefined;

/**
 * Available endpoint descriptions
 * @member {Object.<String, String>} endpoints
 */
V0DatasetsGet200Response.prototype['endpoints'] = undefined;

/**
 * Unique identifier for the job
 * @member {String} job_id
 */
V0DatasetsGet200Response.prototype['job_id'] = undefined;

/**
 * Initial job status
 * @member {module:model/V0DatasetsGet200Response.StatusEnum} status
 */
V0DatasetsGet200Response.prototype['status'] = undefined;

/**
 * Recommended polling interval in milliseconds
 * @member {Number} polling_interval_ms
 */
V0DatasetsGet200Response.prototype['polling_interval_ms'] = undefined;


V0DatasetsGet200Response.OneOf = ["V0DatasetsGet200ResponseOneOf", "V0DatasetsGet200ResponseOneOf1"];

export default V0DatasetsGet200Response;

