/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V0DatasetsJobIdGet200ResponseProgress model module.
 * @module model/V0DatasetsJobIdGet200ResponseProgress
 * @version 0.5.0
 */
class V0DatasetsJobIdGet200ResponseProgress {
    /**
     * Constructs a new <code>V0DatasetsJobIdGet200ResponseProgress</code>.
     * Progress information for a dataset collection job
     * @alias module:model/V0DatasetsJobIdGet200ResponseProgress
     * @param currentStep {String} Current step in the processing pipeline
     * @param rowsCollected {Number} Number of data rows collected so far
     * @param urlsProcessed {Number} Number of URLs processed so far
     * @param urlsTotal {Number} Total number of URLs to process
     * @param lastUpdated {Date} Timestamp of last progress update
     */
    constructor(currentStep, rowsCollected, urlsProcessed, urlsTotal, lastUpdated) { 
        
        V0DatasetsJobIdGet200ResponseProgress.initialize(this, currentStep, rowsCollected, urlsProcessed, urlsTotal, lastUpdated);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentStep, rowsCollected, urlsProcessed, urlsTotal, lastUpdated) { 
        obj['current_step'] = currentStep;
        obj['rows_collected'] = rowsCollected;
        obj['urls_processed'] = urlsProcessed;
        obj['urls_total'] = urlsTotal;
        obj['last_updated'] = lastUpdated;
    }

    /**
     * Constructs a <code>V0DatasetsJobIdGet200ResponseProgress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V0DatasetsJobIdGet200ResponseProgress} obj Optional instance to populate.
     * @return {module:model/V0DatasetsJobIdGet200ResponseProgress} The populated <code>V0DatasetsJobIdGet200ResponseProgress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V0DatasetsJobIdGet200ResponseProgress();

            if (data.hasOwnProperty('current_step')) {
                obj['current_step'] = ApiClient.convertToType(data['current_step'], 'String');
            }
            if (data.hasOwnProperty('rows_collected')) {
                obj['rows_collected'] = ApiClient.convertToType(data['rows_collected'], 'Number');
            }
            if (data.hasOwnProperty('urls_processed')) {
                obj['urls_processed'] = ApiClient.convertToType(data['urls_processed'], 'Number');
            }
            if (data.hasOwnProperty('urls_total')) {
                obj['urls_total'] = ApiClient.convertToType(data['urls_total'], 'Number');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V0DatasetsJobIdGet200ResponseProgress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V0DatasetsJobIdGet200ResponseProgress</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V0DatasetsJobIdGet200ResponseProgress.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['current_step'] && !(typeof data['current_step'] === 'string' || data['current_step'] instanceof String)) {
            throw new Error("Expected the field `current_step` to be a primitive type in the JSON string but got " + data['current_step']);
        }

        return true;
    }


}

V0DatasetsJobIdGet200ResponseProgress.RequiredProperties = ["current_step", "rows_collected", "urls_processed", "urls_total", "last_updated"];

/**
 * Current step in the processing pipeline
 * @member {String} current_step
 */
V0DatasetsJobIdGet200ResponseProgress.prototype['current_step'] = undefined;

/**
 * Number of data rows collected so far
 * @member {Number} rows_collected
 */
V0DatasetsJobIdGet200ResponseProgress.prototype['rows_collected'] = undefined;

/**
 * Number of URLs processed so far
 * @member {Number} urls_processed
 */
V0DatasetsJobIdGet200ResponseProgress.prototype['urls_processed'] = undefined;

/**
 * Total number of URLs to process
 * @member {Number} urls_total
 */
V0DatasetsJobIdGet200ResponseProgress.prototype['urls_total'] = undefined;

/**
 * Timestamp of last progress update
 * @member {Date} last_updated
 */
V0DatasetsJobIdGet200ResponseProgress.prototype['last_updated'] = undefined;






export default V0DatasetsJobIdGet200ResponseProgress;

