/**
 * Qoetry API
 * Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: samuel.tinnerholm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V0PlansGet200ResponsePlansValue from './V0PlansGet200ResponsePlansValue';

/**
 * The V0PlansGet200Response model module.
 * @module model/V0PlansGet200Response
 * @version 0.5.0
 */
class V0PlansGet200Response {
    /**
     * Constructs a new <code>V0PlansGet200Response</code>.
     * Response containing all available plans
     * @alias module:model/V0PlansGet200Response
     * @param plans {Object.<String, module:model/V0PlansGet200ResponsePlansValue>} Plans keyed by plan name
     * @param defaultPlan {String} Default plan name
     */
    constructor(plans, defaultPlan) { 
        
        V0PlansGet200Response.initialize(this, plans, defaultPlan);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, plans, defaultPlan) { 
        obj['plans'] = plans;
        obj['default_plan'] = defaultPlan;
    }

    /**
     * Constructs a <code>V0PlansGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V0PlansGet200Response} obj Optional instance to populate.
     * @return {module:model/V0PlansGet200Response} The populated <code>V0PlansGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V0PlansGet200Response();

            if (data.hasOwnProperty('plans')) {
                obj['plans'] = ApiClient.convertToType(data['plans'], {'String': V0PlansGet200ResponsePlansValue});
            }
            if (data.hasOwnProperty('default_plan')) {
                obj['default_plan'] = ApiClient.convertToType(data['default_plan'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V0PlansGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V0PlansGet200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V0PlansGet200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['default_plan'] && !(typeof data['default_plan'] === 'string' || data['default_plan'] instanceof String)) {
            throw new Error("Expected the field `default_plan` to be a primitive type in the JSON string but got " + data['default_plan']);
        }

        return true;
    }


}

V0PlansGet200Response.RequiredProperties = ["plans", "default_plan"];

/**
 * Plans keyed by plan name
 * @member {Object.<String, module:model/V0PlansGet200ResponsePlansValue>} plans
 */
V0PlansGet200Response.prototype['plans'] = undefined;

/**
 * Default plan name
 * @member {String} default_plan
 */
V0PlansGet200Response.prototype['default_plan'] = undefined;






export default V0PlansGet200Response;

