# coding: utf-8

"""
    Qoetry API

    Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 

    The version of the OpenAPI document: 0.5.0
    Contact: samuel.tinnerholm@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qoery.models.list_plans200_response import ListPlans200Response

class TestListPlans200Response(unittest.TestCase):
    """ListPlans200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPlans200Response:
        """Test ListPlans200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPlans200Response`
        """
        model = ListPlans200Response()
        if include_optional:
            return ListPlans200Response(
                plans = {free={name=Free, description=Ideal for experimentation and testing, price=$0, billing=one-time, limits={datasets=100}, api_keys=1, support=Community}},
                default_plan = 'free'
            )
        else:
            return ListPlans200Response(
                plans = {free={name=Free, description=Ideal for experimentation and testing, price=$0, billing=one-time, limits={datasets=100}, api_keys=1, support=Community}},
                default_plan = 'free',
        )
        """

    def testListPlans200Response(self):
        """Test ListPlans200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
