# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.query_nl_post400_response import QueryNlPost400Response

class TestQueryNlPost400Response(unittest.TestCase):
    """QueryNlPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryNlPost400Response:
        """Test QueryNlPost400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryNlPost400Response`
        """
        model = QueryNlPost400Response()
        if include_optional:
            return QueryNlPost400Response(
                error = '',
                code = 56,
                details = ''
            )
        else:
            return QueryNlPost400Response(
                error = '',
                code = 56,
        )
        """

    def testQueryNlPost400Response(self):
        """Test QueryNlPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
