# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scrape_post200_response_artifacts import ScrapePost200ResponseArtifacts

class TestScrapePost200ResponseArtifacts(unittest.TestCase):
    """ScrapePost200ResponseArtifacts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScrapePost200ResponseArtifacts:
        """Test ScrapePost200ResponseArtifacts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScrapePost200ResponseArtifacts`
        """
        model = ScrapePost200ResponseArtifacts()
        if include_optional:
            return ScrapePost200ResponseArtifacts(
                html_url = '',
                markdown_url = '',
                tables_base_url = ''
            )
        else:
            return ScrapePost200ResponseArtifacts(
        )
        """

    def testScrapePost200ResponseArtifacts(self):
        """Test ScrapePost200ResponseArtifacts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
