# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.data_sources_api import DataSourcesApi


class TestDataSourcesApi(unittest.TestCase):
    """DataSourcesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataSourcesApi()

    def tearDown(self) -> None:
        pass

    def test_scrape_post(self) -> None:
        """Test case for scrape_post

        Scrape URL → return series
        """
        pass


if __name__ == '__main__':
    unittest.main()
