# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 

    The version of the OpenAPI document: 0.4.0
    Contact: samuel.tinnerholm@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qoery.models.plans_get200_response import PlansGet200Response

class TestPlansGet200Response(unittest.TestCase):
    """PlansGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlansGet200Response:
        """Test PlansGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlansGet200Response`
        """
        model = PlansGet200Response()
        if include_optional:
            return PlansGet200Response(
                plans = {
                    'key' : qoery.models._plans_get_200_response_plans_value._plans_get_200_response_plans_value(
                        name = '', 
                        description = '', 
                        price = '', 
                        billing = '', 
                        limits = {
                            'key' : 56
                            }, 
                        api_keys = null, 
                        support = '', 
                        monthly_price = null, 
                        annual_price = null, 
                        discount_percentage = 1.337, )
                    },
                default_plan = ''
            )
        else:
            return PlansGet200Response(
                plans = {
                    'key' : qoery.models._plans_get_200_response_plans_value._plans_get_200_response_plans_value(
                        name = '', 
                        description = '', 
                        price = '', 
                        billing = '', 
                        limits = {
                            'key' : 56
                            }, 
                        api_keys = null, 
                        support = '', 
                        monthly_price = null, 
                        annual_price = null, 
                        discount_percentage = 1.337, )
                    },
                default_plan = '',
        )
        """

    def testPlansGet200Response(self):
        """Test PlansGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
