# coding: utf-8

"""
    Qoetry API

    Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 

    The version of the OpenAPI document: 0.5.0
    Contact: samuel.tinnerholm@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qoery.models.v0_plans_get200_response_plans_value import V0PlansGet200ResponsePlansValue

class TestV0PlansGet200ResponsePlansValue(unittest.TestCase):
    """V0PlansGet200ResponsePlansValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0PlansGet200ResponsePlansValue:
        """Test V0PlansGet200ResponsePlansValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0PlansGet200ResponsePlansValue`
        """
        model = V0PlansGet200ResponsePlansValue()
        if include_optional:
            return V0PlansGet200ResponsePlansValue(
                name = 'Free',
                description = 'Ideal for experimentation and testing',
                price = '$0',
                billing = 'one-time',
                limits = {datasets=100, query/nl=50},
                api_keys = 1,
                support = 'Community',
                monthly_price = None,
                annual_price = None,
                discount_percentage = 0.15
            )
        else:
            return V0PlansGet200ResponsePlansValue(
                name = 'Free',
                description = 'Ideal for experimentation and testing',
                price = '$0',
                billing = 'one-time',
                limits = {datasets=100, query/nl=50},
                api_keys = 1,
                support = 'Community',
        )
        """

    def testV0PlansGet200ResponsePlansValue(self):
        """Test V0PlansGet200ResponsePlansValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
