# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.query_sql_post200_response import QuerySqlPost200Response

class TestQuerySqlPost200Response(unittest.TestCase):
    """QuerySqlPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuerySqlPost200Response:
        """Test QuerySqlPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuerySqlPost200Response`
        """
        model = QuerySqlPost200Response()
        if include_optional:
            return QuerySqlPost200Response(
                series = [
                    openapi_client.models._query_nl_post_200_response_all_of_series_inner._query_nl_post_200_response_allOf_series_inner(
                        series_id = '', 
                        name = '', 
                        unit = '', 
                        observations = [
                            openapi_client.models._query_nl_post_200_response_all_of_series_inner_observations_inner._query_nl_post_200_response_allOf_series_inner_observations_inner(
                                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                value = 1.337, )
                            ], )
                    ]
            )
        else:
            return QuerySqlPost200Response(
                series = [
                    openapi_client.models._query_nl_post_200_response_all_of_series_inner._query_nl_post_200_response_allOf_series_inner(
                        series_id = '', 
                        name = '', 
                        unit = '', 
                        observations = [
                            openapi_client.models._query_nl_post_200_response_all_of_series_inner_observations_inner._query_nl_post_200_response_allOf_series_inner_observations_inner(
                                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                value = 1.337, )
                            ], )
                    ],
        )
        """

    def testQuerySqlPost200Response(self):
        """Test QuerySqlPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
