# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 

    The version of the OpenAPI document: 0.2.0
    Contact: samuel.tinnerholm@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qoery.models.query_nl_post200_response_series_inner_observations_inner import QueryNlPost200ResponseSeriesInnerObservationsInner

class TestQueryNlPost200ResponseSeriesInnerObservationsInner(unittest.TestCase):
    """QueryNlPost200ResponseSeriesInnerObservationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryNlPost200ResponseSeriesInnerObservationsInner:
        """Test QueryNlPost200ResponseSeriesInnerObservationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryNlPost200ResponseSeriesInnerObservationsInner`
        """
        model = QueryNlPost200ResponseSeriesInnerObservationsInner()
        if include_optional:
            return QueryNlPost200ResponseSeriesInnerObservationsInner(
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                value = None
            )
        else:
            return QueryNlPost200ResponseSeriesInnerObservationsInner(
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                value = None,
        )
        """

    def testQueryNlPost200ResponseSeriesInnerObservationsInner(self):
        """Test QueryNlPost200ResponseSeriesInnerObservationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
