# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call.  # Installation  ### Python SDK  Install from PyPI:  ```bash pip install qoery ```  PyPI: [qoery](https://pypi.org/project/qoery/)  ### JavaScript SDK  Install from npm:  ```bash npm install qoery ```  npm: [qoery](https://www.npmjs.com/package/qoery) 

    The version of the OpenAPI document: 0.2.0
    Contact: samuel.tinnerholm@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qoery.models.scrape_get200_response_artifacts import ScrapeGet200ResponseArtifacts

class TestScrapeGet200ResponseArtifacts(unittest.TestCase):
    """ScrapeGet200ResponseArtifacts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScrapeGet200ResponseArtifacts:
        """Test ScrapeGet200ResponseArtifacts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScrapeGet200ResponseArtifacts`
        """
        model = ScrapeGet200ResponseArtifacts()
        if include_optional:
            return ScrapeGet200ResponseArtifacts(
                html_url = '',
                markdown_url = '',
                tables_base_url = ''
            )
        else:
            return ScrapeGet200ResponseArtifacts(
        )
        """

    def testScrapeGet200ResponseArtifacts(self):
        """Test ScrapeGet200ResponseArtifacts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
