# coding: utf-8

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.query_nl_post200_response_series_inner import QueryNlPost200ResponseSeriesInner

class TestQueryNlPost200ResponseSeriesInner(unittest.TestCase):
    """QueryNlPost200ResponseSeriesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryNlPost200ResponseSeriesInner:
        """Test QueryNlPost200ResponseSeriesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryNlPost200ResponseSeriesInner`
        """
        model = QueryNlPost200ResponseSeriesInner()
        if include_optional:
            return QueryNlPost200ResponseSeriesInner(
                series_id = '',
                name = '',
                unit = '',
                observations = [
                    openapi_client.models._query_nl_post_200_response_series_inner_observations_inner._query_nl_post_200_response_series_inner_observations_inner(
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        value = 1.337, )
                    ]
            )
        else:
            return QueryNlPost200ResponseSeriesInner(
                name = '',
                observations = [
                    openapi_client.models._query_nl_post_200_response_series_inner_observations_inner._query_nl_post_200_response_series_inner_observations_inner(
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        value = 1.337, )
                    ],
        )
        """

    def testQueryNlPost200ResponseSeriesInner(self):
        """Test QueryNlPost200ResponseSeriesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
