# coding: utf-8

"""
    Qoetry API

    Qoetry API for dataset collection and management. Start dataset collection jobs, monitor their progress, and download results as CSV files.  ## Authentication  **All endpoints require API key authentication** (except `/health` and `/`).  You can provide your API key via: - Query parameter: `?api_key=your_api_key` - Header: `x-api-key: your_api_key` - Header: `Authorization: Bearer your_api_key`  ## Rate Limits  API calls are subject to monthly quotas based on your subscription plan. Quota information is available via the `/v0/usage` endpoint. 

    The version of the OpenAPI document: 0.5.0
    Contact: samuel.tinnerholm@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from qoery.models.get_usage_stats200_response import GetUsageStats200Response

from qoery.api_client import ApiClient, RequestSerialized
from qoery.api_response import ApiResponse
from qoery.rest import RESTResponseType


class UsageApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_usage_stats(
        self,
        api_key: Annotated[Optional[StrictStr], Field(description="API key to look up usage for (alternative to uid)")] = None,
        uid: Annotated[Optional[StrictStr], Field(description="User ID to look up usage for (alternative to api_key)")] = None,
        x_api_key: Annotated[Optional[StrictStr], Field(description="API key provided via header")] = None,
        authorization: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="API key provided as Bearer token")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetUsageStats200Response:
        """Get usage statistics

        Returns current usage statistics and quota information for the user. Can be identified by either `api_key` or `uid` parameter.  **Usage Period:** - Usage is tracked monthly, resetting on the 1st of each month - Counts include all API calls, including errors - Errors are tracked separately in the `errors` field 

        :param api_key: API key to look up usage for (alternative to uid)
        :type api_key: str
        :param uid: User ID to look up usage for (alternative to api_key)
        :type uid: str
        :param x_api_key: API key provided via header
        :type x_api_key: str
        :param authorization: API key provided as Bearer token
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_usage_stats_serialize(
            api_key=api_key,
            uid=uid,
            x_api_key=x_api_key,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetUsageStats200Response",
            '400': "ListDatasetsOrStartJob400Response",
            '401': "ListDatasetsOrStartJob400Response",
            '500': "ListDatasetsOrStartJob400Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_usage_stats_with_http_info(
        self,
        api_key: Annotated[Optional[StrictStr], Field(description="API key to look up usage for (alternative to uid)")] = None,
        uid: Annotated[Optional[StrictStr], Field(description="User ID to look up usage for (alternative to api_key)")] = None,
        x_api_key: Annotated[Optional[StrictStr], Field(description="API key provided via header")] = None,
        authorization: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="API key provided as Bearer token")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetUsageStats200Response]:
        """Get usage statistics

        Returns current usage statistics and quota information for the user. Can be identified by either `api_key` or `uid` parameter.  **Usage Period:** - Usage is tracked monthly, resetting on the 1st of each month - Counts include all API calls, including errors - Errors are tracked separately in the `errors` field 

        :param api_key: API key to look up usage for (alternative to uid)
        :type api_key: str
        :param uid: User ID to look up usage for (alternative to api_key)
        :type uid: str
        :param x_api_key: API key provided via header
        :type x_api_key: str
        :param authorization: API key provided as Bearer token
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_usage_stats_serialize(
            api_key=api_key,
            uid=uid,
            x_api_key=x_api_key,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetUsageStats200Response",
            '400': "ListDatasetsOrStartJob400Response",
            '401': "ListDatasetsOrStartJob400Response",
            '500': "ListDatasetsOrStartJob400Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_usage_stats_without_preload_content(
        self,
        api_key: Annotated[Optional[StrictStr], Field(description="API key to look up usage for (alternative to uid)")] = None,
        uid: Annotated[Optional[StrictStr], Field(description="User ID to look up usage for (alternative to api_key)")] = None,
        x_api_key: Annotated[Optional[StrictStr], Field(description="API key provided via header")] = None,
        authorization: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="API key provided as Bearer token")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get usage statistics

        Returns current usage statistics and quota information for the user. Can be identified by either `api_key` or `uid` parameter.  **Usage Period:** - Usage is tracked monthly, resetting on the 1st of each month - Counts include all API calls, including errors - Errors are tracked separately in the `errors` field 

        :param api_key: API key to look up usage for (alternative to uid)
        :type api_key: str
        :param uid: User ID to look up usage for (alternative to api_key)
        :type uid: str
        :param x_api_key: API key provided via header
        :type x_api_key: str
        :param authorization: API key provided as Bearer token
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_usage_stats_serialize(
            api_key=api_key,
            uid=uid,
            x_api_key=x_api_key,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetUsageStats200Response",
            '400': "ListDatasetsOrStartJob400Response",
            '401': "ListDatasetsOrStartJob400Response",
            '500': "ListDatasetsOrStartJob400Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_usage_stats_serialize(
        self,
        api_key,
        uid,
        x_api_key,
        authorization,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if api_key is not None:
            
            _query_params.append(('api_key', api_key))
            
        if uid is not None:
            
            _query_params.append(('uid', uid))
            
        # process the header parameters
        if x_api_key is not None:
            _header_params['x-api-key'] = x_api_key
        if authorization is not None:
            _header_params['Authorization'] = authorization
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v0/usage',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


