# coding: utf-8

# flake8: noqa

"""
    qoery's API

    Every number on the internet, queryable. Instant access to millions of trusted statistics through a single natural language query or API call. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DataSourcesApi",
    "QueriesApi",
    "UsageApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ErrorResponse",
    "NLQueryRequest",
    "Observation",
    "QueryNlPost200Response",
    "QueryNlPost200ResponseSeriesInner",
    "QueryNlPost200ResponseSeriesInnerObservationsInner",
    "QueryNlPost400Response",
    "QueryNlPostRequest",
    "QueryResponse",
    "QuerySqlPostRequest",
    "SQLQueryRequest",
    "ScrapePostRequest",
    "Series",
    "URLRequest",
    "UsageGet200Response",
    "UsageStats",
]

# import apis into sdk package
from openapi_client.api.data_sources_api import DataSourcesApi as DataSourcesApi
from openapi_client.api.queries_api import QueriesApi as QueriesApi
from openapi_client.api.usage_api import UsageApi as UsageApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.error_response import ErrorResponse as ErrorResponse
from openapi_client.models.nl_query_request import NLQueryRequest as NLQueryRequest
from openapi_client.models.observation import Observation as Observation
from openapi_client.models.query_nl_post200_response import QueryNlPost200Response as QueryNlPost200Response
from openapi_client.models.query_nl_post200_response_series_inner import QueryNlPost200ResponseSeriesInner as QueryNlPost200ResponseSeriesInner
from openapi_client.models.query_nl_post200_response_series_inner_observations_inner import QueryNlPost200ResponseSeriesInnerObservationsInner as QueryNlPost200ResponseSeriesInnerObservationsInner
from openapi_client.models.query_nl_post400_response import QueryNlPost400Response as QueryNlPost400Response
from openapi_client.models.query_nl_post_request import QueryNlPostRequest as QueryNlPostRequest
from openapi_client.models.query_response import QueryResponse as QueryResponse
from openapi_client.models.query_sql_post_request import QuerySqlPostRequest as QuerySqlPostRequest
from openapi_client.models.sql_query_request import SQLQueryRequest as SQLQueryRequest
from openapi_client.models.scrape_post_request import ScrapePostRequest as ScrapePostRequest
from openapi_client.models.series import Series as Series
from openapi_client.models.url_request import URLRequest as URLRequest
from openapi_client.models.usage_get200_response import UsageGet200Response as UsageGet200Response
from openapi_client.models.usage_stats import UsageStats as UsageStats
